//! DEPENDENCIES.toml: the publisher-side fix for the one structural
//! regression the telescope carries relative to the retired chain
//! design -- a foreign telescope's fold ORDER lives in the
//! receiver's config, not in the data (5_plan.org, work item
//! dependencies-manifest; decided in 4_discussion, "lets Skg
//! automatically generate a DEPENDENCIES.toml").
//!
//! PUBLISHER half: at init, every OWNED Skg repo directory gets a
//! DEPENDENCIES.toml whose `dependencies` is a list of pairs, one per
//! Skg repo its telescope sections may reference -- itself and
//! everything more public, in privacy order, the Skg repo itself last.
//! Each pair says where a receiver can fetch that Skg repo: `path`
//! (data-root-relative, author-namespaced, which is what a receiver
//! actually downloads) and `git-remote` (the Skg repo's fetch URL,
//! `origin` preferred, else the first remote with its name recorded
//! in `git-remote-name`; omitted when the Skg repo is not a git repo or
//! has no remote). The last pair is the manifest's own Skg repo, so its
//! own remote falls out for free. skg makes no use of the git-remote
//! values itself. Clobbering a preexisting manifest is a feature;
//! writes are byte-stable.
//!
//! RECEIVER half: at config validation, a FOREIGN Skg repo carrying a
//! manifest is read, its entries matched to the receiver's repos
//! by final path component (the repo name -- the receiver's author
//! folder for the publisher differs from the publisher's "owned").
//! When the receiver's privacy order contradicts the manifest's
//! relative order, warn and suggest the fix; never reorder
//! automatically.

use crate::git_ops::read_gitrepo::repo_git_remote;
use crate::types::misc::{SkgConfig, RepoName};

use std::io;
use std::path::PathBuf;

/// Quote a value as a TOML basic string, escaping the two characters
/// that would otherwise break out of the quotes. Enough for git
/// remote URLs and Skg repo paths, which carry no control characters.
fn toml_basic_string (s : &str) -> String {
  let escaped : String =
    s . replace ('\\', "\\\\") . replace ('"', "\\\"");
  format! ("\"{}\"", escaped) }

/// One `dependencies` entry: a Skg repo a manifest's telescope sections
/// may reference, and where a receiver can fetch it.
struct DependencyEntry {
  path   : String,                    // data-root-relative directory
  remote : Option<(String, String)>,  // (remote name, fetch URL)
}

/// Render a `DependencyEntry` as one inline-table line of the
/// `dependencies` list: `{ path = "...", git-remote = "..." },`.
/// `git-remote` is omitted when the Skg repo has no remote;
/// `git-remote-name` appears only for a non-`origin` remote.
fn render_dependency_entry (entry : &DependencyEntry) -> String {
  let mut fields : String =
    format! ("path = {}", toml_basic_string (&entry . path));
  if let Some ((remote_name, remote_url)) = &entry . remote {
    fields . push_str ( & format! (
      ", git-remote = {}", toml_basic_string (remote_url) ));
    if remote_name != "origin" {
      fields . push_str ( & format! (
        ", git-remote-name = {}",
        toml_basic_string (remote_name) )); }}
  format! ("  {{ {} }},\n", fields) }

/// The publisher half. Call after config load; returns the repos
/// whose manifests were (re)written.
pub fn write_dependencies_manifests (
  config : &SkgConfig,
) -> io::Result<Vec<RepoName>> {
  let ordered : Vec<RepoName> = config . ordered_repos ();
  let mut written : Vec<RepoName> = Vec::new ();
  for (position, name) in ordered . iter () . enumerate () {
    if ! config . user_owns_repo (name) { continue; }
    let Some (skgrepo) = config . repos . get (name) else {
      continue; };
    if ! skgrepo . path . is_dir () { continue; }
    let dependencies : Vec<DependencyEntry> =
      ordered [..= position] . iter ()
      . filter_map ( |n| {
          let dep_repo = config . repos . get (n) ?;
          let path : String =
            dep_repo . path
            . strip_prefix ( &config . data_root )
            . map ( |p| p . to_string_lossy () . into_owned () )
            . unwrap_or_else (
              |_| dep_repo . path
                  . to_string_lossy () . into_owned () );
          Some ( DependencyEntry {
            path,
            remote : repo_git_remote (&dep_repo . path), } ) } )
      . collect ();
    let content : String = {
      let mut c : String = String::new ();
      c . push_str (
        "# Generated by skg; regenerated at every server start, so\n\
         # hand edits will be clobbered (that is a feature: it stays\n\
         # true to the publisher's config). Each dependency is a Skg\n\
         # repo this Skg repo's telescope sections may reference --\n\
         # itself and everything more public, MOST PUBLIC FIRST, the\n\
         # Skg repo itself last. A receiver should order these the same\n\
         # way relative to one another, or the privacy telescopes\n\
         # spanning them will fold in the wrong order. `path` is the\n\
         # data-root-relative directory; `git-remote` is where a\n\
         # receiver can fetch it (the fetch URL `git remote -v`\n\
         # prints, `origin` preferred), omitted when the Skg repo is\n\
         # not a Git repo or has no remote; `git-remote-name` names\n\
         # the remote only when it is not the conventional \"origin\".\n\
         # skg makes no use of the git-remote values itself.\n" );
      c . push_str ("dependencies = [\n");
      for entry in &dependencies {
        c . push_str ( & render_dependency_entry (entry) ); }
      c . push_str ("]\n");
      c };
    let manifest_path : PathBuf =
      skgrepo . path . join ("DEPENDENCIES.toml");
    let unchanged : bool = // byte-stability
      std::fs::read_to_string (&manifest_path)
      . map ( |old| old == content )
      . unwrap_or (false);
    if ! unchanged {
      std::fs::write (&manifest_path, content) ?; }
    written . push ( name . clone () ); }
  Ok (written) }

/// The `path` of one `dependencies` entry. New format: an inline
/// table carrying a `path` key. Older format: a bare string. Accept
/// either, so a foreign manifest still in the string shape keeps
/// yielding ordering warnings.
fn dependency_entry_path (e : &toml::Value) -> Option<String> {
  e . as_str () . map ( str::to_string )
    . or_else ( || e . get ("path")
                . and_then ( |p| p . as_str () )
                . map ( str::to_string )) }

/// The receiver half: warnings (never errors, never reordering) for
/// each foreign manifest whose relative order the receiver's config
/// contradicts. Returned as strings so init can log them and tests
/// can pin them.
pub fn foreign_manifest_order_warnings (
  config : &SkgConfig,
) -> Vec<String> {
  let ordered : Vec<RepoName> = config . ordered_repos ();
  let final_component = |p : &std::path::Path| -> Option<String> {
    p . components () . next_back ()
      . and_then ( |c| match c {
        std::path::Component::Normal (s) =>
          Some ( s . to_string_lossy () . into_owned () ),
        _ => None } ) };
  // receiver position by repo name (final path component)
  let receiver_position_of = |gitrepo : &str| -> Option<usize> {
    ordered . iter () . position ( |n|
      config . repos . get (n)
      . and_then ( |s| final_component ( &s . path ))
      . as_deref () == Some (gitrepo) ) };
  let mut warnings : Vec<String> = Vec::new ();
  for name in &ordered {
    if config . user_owns_repo (name) { continue; }
    let Some (skgrepo) = config . repos . get (name) else {
      continue; };
    let manifest_path : PathBuf =
      skgrepo . path . join ("DEPENDENCIES.toml");
    let Ok (contents) =
      std::fs::read_to_string (&manifest_path) else { continue; };
    let entries : Vec<String> =
      toml::from_str::<toml::Value> (&contents) . ok ()
      . as_ref ()
      . and_then ( |v| v . get ("dependencies") )
      . and_then ( |d| d . as_array () )
      . map ( |arr| arr . iter ()
              . filter_map ( dependency_entry_path )
              . collect () )
      . unwrap_or_default ();
    // The manifest's entries, restricted to repos the receiver also
    // has, must appear in the receiver's order.
    let mut last : Option<(String, usize)> = None;
    for entry in &entries {
      let gitrepo : Option<String> =
        final_component ( std::path::Path::new (entry) );
      let Some (gitrepo) = gitrepo else { continue; };
      let Some (position) = receiver_position_of (&gitrepo) else {
        continue; };
      if let Some ((prev_gitrepo, prev_position)) = &last {
        if position < *prev_position {
          warnings . push ( format! (
            "Repo '{}' ships a DEPENDENCIES.toml placing '{}' more public than '{}', but this config orders them the other way. Telescopes spanning them will fold in the publisher-unintended order; consider reordering [[repos]].",
            name, prev_gitrepo, gitrepo )); }}
      last = Some ((gitrepo, position)); }}
  warnings }

#[cfg(test)]
#[path = "../../tests/unit/dependencies_manifest.rs"]
mod tests;
