* To know about the project,
  These resources cover the space decently, with some redundacy.
** README.org
** api-and-formats.md
** the coding-advice/ folder
** schema.tql
** https://github.com/JeffreyBenjaminBrown/public_notes_with_github-navigable_links/blob/main/shareable_knowledge_gardens.org
** TODO.org
** anything the above link to
* I find you easiest to read
  in an org file on disk, rather than inside this CLI.
  For anything longer than a couple paragraphs,
  please refer me to a file.
* Please report problems in the code.
Whether or not my latest request takes such things into consideration,
if you find any:

- bugs or deviations from spec
- noteworthy inefficiencies
- opportunities to improve the architecture

please report them, in a top-level file 'problems.org'.
If it doesn't exist, please create that.
* Please report problems with my requests.
For each of my requests, push back against anything vague or ill-specified, inefficient, unnecessary or overly complex.
* Thanks,
  Jeff
