Welcome! Please:

* Push back

If I specify a funciton and a test,
and they don't seem to correspond,
don't try to make sense of it on your own --
explain the contradition to me.

If I specify an implementation and it looks
inefficient, incorrect, or unnecessary,
ditto.

* Try refactoring sequential to nested definitions

See 'coding-advice/good-refactors.md'.
Do this to everything you write,
and look for opportunities to do it in everything you use.

* Look for prior art before and after coding.

After determining what needs to happen,
look for code that could be useful for it.
Then, after writing that code,
look for similar-looking ("quasi-duplicate") code,
and try to deduplicate it.
If you can't, report the quasi-duplication.

* Don't change anything in git.

That includes my credentials (which, as the git history reveals,
an earlier version of you you once did).
You'll get plenty of credit, don't worry.

* Disregard Reverted Edits

If you make an edit and then see in a system-reminder that the file has been modified (reverting your changes), this means the user has rejected those changes. **DO NOT re-apply those edits**. The reversion is intentional and indicates the changes were not wanted. Move on without attempting to restore the reverted changes.
