db_name = "skg-dev"
tantivy_folder = ".index.tantivy"
port = 1730 # TCP port for Rust-Emacs API communication.

[[sources]]
name = "private"
path = "private"
user_owns_it = true

[[sources]]
name = "public"
path = "public"
user_owns_it = true

[[sources]]
name = "Fred"
path = "Fred"
user_owns_it = false
