* rewriting how buffer update works
** relevant prior art
   Search for functions with 'integrate' or 'complete' in the name
   to see how some of these ideas have been implemented,
   albeit likely in a less principled way, already.
** how it currently works
 A call graph can be found at
 tools/introspect/call-graph/output/update_from_and_rerender_buffer.org
*** skgnode_map : SkgNodeMap
    incomplete, hence the importance of
      skgnode_from_map_or_disk
*** source_diffs : Option<HashMap<SourceName, SourceDiff>>
    only for git-diff view
*** deleted_id_src_map : HashMap<ID, SourceName>
*** complete_or_restore_each_node_in_branch
**** allow indef nodes to be missing content
     don't complete their content
**** correct the aliasCol in an indef node
     It can't be wrong in a def node,
     so it doesn't need correcting there.
**** correct the SubscribeeCol in an indef node
     It can't be wrong in a def node
     so it doesn't need correcting there.
**** detect_and_mark_cycle
**** make_indef_if_repeat_then_extend_defmap
**** clobberIndefinitiveOrgnode
**** maybe_add_subscribeeCol_branch
*** view_requests : Vec < (NodeId, ViewRequest) >
    Was just for speed.
    Should instead interleave with other completion ops,
    but for each node perform view requests last,
    so that they can be integrated with overlapping content.
*** set_metadata_relationship_viewdata_in_forest
** how to redo it
*** write these functions
**** completeAliasCol
     Take a treenode, a tree and a skgnodemap.
     Verify that the node is an AliasCol.
     Visits its parent, verifies it's a truenode,
     fetch the corresponding skgnode from the map,
     and reads the aliases into a variable
     'aliases' (a list of strings).
     'Complete' the AliasCol's children against 'aliases':

     First partition the AliasCol's children into two sets:
     truenodes with parentIgnores, and Alias nodes.
       (If anything does not fit those two categories,
       throw an error to the caller.)
     Put all the ignored truenodes first.
     Among the aliases, discard any whose text is not in 'aliases'.
     Create a new Alias node for each value in 'aliases'
     not found among the Alias treenodes.
     Add those new Alias treenodes to its Alias children,
     such that the resulting list of Alias children
     is equal to 'aliases', and in the same order.
*** do these, in serial
**** DFS postorder (child-first) completion
***** forestroot: nothing to do
***** alias col
      read your parent, and then
      order and complete its aliases among your children
***** alias: nothing to do
      but add a comment: for its own correctness, an alias must
        rely on its parent's having been processed correctly
***** HiddenInSubscribeeCol
      Read your parent (Subscribee) and grandparent (Subscriber),
      find everything subscriber hides that subscribee contains,
      and ensure your children are only those, and in order.
      Mark anything else 'parentIgnores'.
      If you have no children, remove yourself.
***** HiddenOutsideOfSubscribeeCol
      Read your siblings (subscribees) and parent (subscriber).
      Ensure that your children are, and in order,
        only what the subscriber hides that no subscribee contains.
      If you have no children, remove yourself.
***** ID: nothing to do
      but add a comment: For correctness, an ID relies on
        its parent having been handled correctly.
***** IDCol
      Ensure that your children are only, and in order,
        the IDs of your parent.
***** SubscribeeCol
      read your parent, and then
      - ensure your non-ignored truenode children
        include all of its subscribees
      - mark any other truenode children 'parentIgnores',
        and move them to before the subscribees
      - append, after all the others, a HiddenOutsideOfSubscribeeCol
        (which will be removed if it would be childless).
        TRICKY: The HiddenOutsideOfSubscribeeCol
        must be processed after all the subscribees,
        so it can determine what they have already excluded.
***** TrueNode
****** apply make_indef_if_repeat_then_extend_defmap to it
****** mark its erroneous content children as parent-ignores
       'erroneous content children' are truenode children
       not marked parentIgnores but not among its content
****** reorder children and complete content
       Ensure your non-ignored truenode children are, and in order,
       equal to your contents.
       Reorder children to be non-truenodes,
       then parentIgnored truenodes, then content truenodes.
***** TextChanged
      Nothing to rewrite -- this is more easily
      deleted from the buffer and respawned fresh.
      Add a comment to that effect.
**** compute GraphNodeStats
     the function is currently called
       set_metadata_relationship_viewdata_in_forest
     but should be renamed
       set_graphnodestats_in_forest
**** compute ViewNodeStats
     This currently happens in two places.
     They should be collected into a single function,
       set_viewnodestats_in_forest
***** detect_and_mark_cycle
***** somewhere else
*** notes and complications
**** Contra previously, we correct aliases and other 'regenerables'
     As the code courrently stands, regenerating them.
     See the function remove_regenerable_scaffolds.
**** TrueNode content completion should include 'phantoms'
     when in git diff view.
     I haven't described how to find those,
     but it's already implemented somewhere.
     For purposes of this plan they should be treated like content,
     even though they are not content (anymore).
