//! Durable, process-owned evidence published before candidate selection.
//!
//! The client archive proves that editor state is recoverable.  This bundle
//! proves what the server is about to do to the derived stores and gives a
//! restarted process immutable G0/G1 reconstruction inputs.  It is published
//! as one private directory rename before the first store mutation.

use super::candidate::{
  ObservedDiskCandidate,
  SemanticChangeEvidence,
  SemanticNodeEvidence,
  config_file_blake3,
  config_identity,
  source_catalog_blake3,
};
use super::journal::MaintenanceJournalStore;
use super::types::{ActiveMaintenance, CandidateSummary, IncidentId, MaintenanceEpoch};
use crate::save::nodecompletes_from_graph;
use crate::types::misc::{ID, SkgConfig, SourceName};
use crate::types::save::{DefineNode, DeleteNode, SaveNode};
use crate::types::store_state::{
  GraphGeneration,
  ManifestRevision,
  SelectedPathManifest,
  SelectedStoreState,
};

use serde::{Deserialize, Serialize};
use sexp::{Atom, Sexp};
use sha2::{Digest, Sha256};
use std::collections::{BTreeMap, BTreeSet};
use std::fs::{self, File, OpenOptions};
use std::io::{Read, Write};
use std::path::{Path, PathBuf};

#[cfg(unix)]
use std::os::unix::fs::{
  DirBuilderExt,
  MetadataExt,
  OpenOptionsExt,
  PermissionsExt,
};

const EVIDENCE_FORMAT_VERSION : u32 = 2;
pub const CLIENT_EVIDENCE_FORMAT_VERSION : u32 = 1;

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct MaintenanceEvidenceBundle {
  pub format_version       : u32,
  pub incident_id          : IncidentId,
  pub maintenance_epoch    : MaintenanceEpoch,
  pub candidate             : CandidateSummary,
  pub config_identity       : PathBuf,
  pub config_file_blake3    : String,
  pub source_catalog_blake3 : String,
  pub g0_graph_generation   : GraphGeneration,
  pub g0_manifest_revision  : ManifestRevision,
  pub g0_manifest           : SelectedPathManifest,
  pub g1_manifest           : SelectedPathManifest,
  pub g0_nodes              : Vec<SemanticNodeEvidence>,
  pub g1_nodes              : Vec<SemanticNodeEvidence>,
  pub transition_delta      : Vec<EvidenceDefinition>,
  pub added_primary_ids     : BTreeSet<ID>,
  pub deleted_primary_ids   : BTreeSet<ID>,
  pub modified_primary_ids  : BTreeSet<ID>,
  pub semantic_evidence     : BTreeMap<ID, SemanticChangeEvidence>,
  pub warnings              : Vec<String>,
  pub artifacts             : Vec<EvidenceArtifact>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "kebab-case", tag = "kind")]
pub enum EvidenceDefinition {
  Save { node : SemanticNodeEvidence },
  Delete { id : ID, source : SourceName },
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct EvidenceArtifact {
  pub relative_path : PathBuf,
  pub purpose       : String,
  pub source_path   : Option<PathBuf>,
  pub byte_length   : u64,
  pub sha256        : String,
  pub blake3        : String,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
struct EvidenceEnvelope {
  payload        : MaintenanceEvidenceBundle,
  payload_blake3 : String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PublishedMaintenanceEvidence {
  pub path             : PathBuf,
  pub bundle_sha256    : String,
  pub artifact_count   : usize,
  pub total_file_bytes : u64,
}

/// One exact slice in the opaque payload sent to the client.  Relative paths
/// are generated by the server and contain only safe components; source paths
/// remain content inside the corresponding `sources.sexp` artifact.
#[derive(Clone, Debug, Eq, PartialEq, Serialize)]
pub struct ClientEvidenceArtifact {
  pub key           : String,
  pub relative_path : String,
  pub purpose       : String,
  pub byte_offset   : u64,
  pub byte_length   : u64,
  pub sha256        : String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ClientEvidenceBundle {
  pub incident_id       : IncidentId,
  pub maintenance_epoch : MaintenanceEpoch,
  pub candidate          : CandidateSummary,
  pub server_bundle_sha256 : String,
  pub transfer_manifest_sha256 : String,
  pub artifact_bytes_sha256 : String,
  pub artifacts          : Vec<ClientEvidenceArtifact>,
  pub bytes              : Vec<u8>,
}

#[derive(Clone, Debug)]
pub struct MaintenanceEvidenceStore {
  directory       : PathBuf,
  config_identity : PathBuf,
}

struct ArtifactBytes {
  metadata : EvidenceArtifact,
  bytes    : Vec<u8>,
}

impl MaintenanceEvidenceStore {
  pub fn alongside (journal : &MaintenanceJournalStore) -> Self {
    Self {
      directory: journal . directory () . join ("evidence"),
      config_identity: journal . config_identity () . to_path_buf (),
    }
  }

  #[cfg(test)]
  fn at_root (directory : PathBuf, config_identity : PathBuf) -> Self {
    Self { directory, config_identity }
  }

  pub fn publish_candidate (
    &self,
    active    : &ActiveMaintenance,
    config    : &SkgConfig,
    selected  : &SelectedStoreState,
    candidate : &ObservedDiskCandidate,
  ) -> Result<PublishedMaintenanceEvidence, String> {
    validate_candidate_contract (active, config, selected, candidate)?;
    create_private_directory_all (&self . directory)?;
    let final_path = self . directory . join (active . incident_id . as_str ());
    if final_path . exists () {
      let (bundle, publication) = self . load (&active . incident_id)?;
      if bundle . candidate == candidate . summary {
        return Ok (publication); }
      // A candidate can become stale after its bundle is durable but before
      // the first store mutation.  Preserve that attempted evidence under a
      // unique sibling and free the canonical incident path for the exact
      // replacement candidate.  Nothing is deleted or overwritten.
      let superseded_path = self . directory . join (format! (
        "{}--superseded--{}--{}",
        active . incident_id, bundle . candidate . id, uuid::Uuid::new_v4 ()));
      fs::rename (&final_path, &superseded_path)
        . map_err (|error| format! (
          "could not preserve superseded candidate evidence: {}", error))?;
      sync_directory (&self . directory)?;
    }

    let temporary = self . directory . join (format! (
      ".{}.{}.tmp", active . incident_id, uuid::Uuid::new_v4 ()));
    create_private_directory (&temporary)?;
    let result = (|| {
      let (mut bundle, artifacts) = build_bundle (
        active, config, selected, candidate)?;
      for artifact in &artifacts {
        let path = temporary . join (&artifact . metadata . relative_path);
        let parent = path . parent ()
          . ok_or_else (|| "evidence artifact has no parent" . to_string ())?;
        create_private_directory_all (parent)?;
        write_private_file (&path, &artifact . bytes)?;
      }
      bundle . artifacts = artifacts . iter ()
        . map (|artifact| artifact . metadata . clone ()) . collect ();
      let payload_bytes = serde_yaml::to_string (&bundle)
        . map_err (|error| error . to_string ())? . into_bytes ();
      let envelope = EvidenceEnvelope {
        payload: bundle,
        payload_blake3: blake3_hex (&payload_bytes),
      };
      let envelope_bytes = serde_yaml::to_string (&envelope)
        . map_err (|error| error . to_string ())? . into_bytes ();
      write_private_file (&temporary . join ("bundle.yaml"), &envelope_bytes)?;
      sync_tree_directories (&temporary)?;
      validate_evidence_directory (
        &temporary, &self . config_identity, Some (&active . incident_id))?;
      fs::rename (&temporary, &final_path)
        . map_err (|error| error . to_string ())?;
      sync_directory (&self . directory)?;
      let (_, publication) = self . load (&active . incident_id)?;
      Ok (publication)
    })();
    // Incomplete temporary directories are intentionally retained.  They are
    // crash evidence and, unlike the final path, never grant mutation authority.
    result
  }

  pub fn load (
    &self,
    incident : &IncidentId,
  ) -> Result<(MaintenanceEvidenceBundle, PublishedMaintenanceEvidence), String> {
    validate_evidence_directory (
      &self . directory . join (incident . as_str ()),
      &self . config_identity,
      Some (incident))
  }

  /// Re-read the already-published evidence and concatenate its declared
  /// client artifacts in manifest order.  Every slice is rechecked after the
  /// read, so a replay never transmits bytes under an obsolete checksum.
  pub fn client_bundle (
    &self,
    incident : &IncidentId,
  ) -> Result<ClientEvidenceBundle, String> {
    let (bundle, publication) = self . load (incident)?;
    let mut bytes = Vec::new ();
    let mut records = Vec::new ();
    for (index, artifact) in bundle . artifacts . iter () . enumerate () {
      let relative_path = artifact . relative_path . to_str ()
        . ok_or_else (|| "client evidence path is not UTF-8" . to_string ())?
        . to_string ();
      let artifact_bytes = fs::read (
        publication . path . join (&artifact . relative_path))
        . map_err (|error| error . to_string ())?;
      if artifact_bytes . len () as u64 != artifact . byte_length
      || sha256_hex (&artifact_bytes) != artifact . sha256
      || blake3_hex (&artifact_bytes) != artifact . blake3
      {
        return Err (format! (
          "evidence artifact changed before transfer: {}", relative_path)); }
      let byte_offset = bytes . len () as u64;
      bytes . extend_from_slice (&artifact_bytes);
      records . push (ClientEvidenceArtifact {
        key: format! ("artifact-{:08}", index),
        relative_path,
        purpose: artifact . purpose . clone (),
        byte_offset,
        byte_length: artifact . byte_length,
        sha256: artifact . sha256 . clone (),
      });
    }
    let artifact_bytes_sha256 = sha256_hex (&bytes);
    let transfer_manifest_sha256 = client_transfer_manifest_sha256 (
      &bundle . incident_id, bundle . maintenance_epoch, &bundle . candidate,
      &publication . bundle_sha256, &artifact_bytes_sha256, &records)?;
    Ok (ClientEvidenceBundle {
      incident_id: bundle . incident_id,
      maintenance_epoch: bundle . maintenance_epoch,
      candidate: bundle . candidate,
      server_bundle_sha256: publication . bundle_sha256,
      transfer_manifest_sha256,
      artifact_bytes_sha256,
      artifacts: records,
      bytes,
    })
  }
}

#[derive(Serialize)]
struct ClientEvidenceTransferManifest<'a> {
  format_version        : u32,
  incident_id           : &'a IncidentId,
  maintenance_epoch     : MaintenanceEpoch,
  candidate             : &'a CandidateSummary,
  server_bundle_sha256  : &'a str,
  artifact_bytes_sha256 : &'a str,
  artifacts             : &'a [ClientEvidenceArtifact],
}

fn client_transfer_manifest_sha256 (
  incident_id           : &IncidentId,
  maintenance_epoch     : MaintenanceEpoch,
  candidate             : &CandidateSummary,
  server_bundle_sha256  : &str,
  artifact_bytes_sha256 : &str,
  artifacts             : &[ClientEvidenceArtifact],
) -> Result<String, String> {
  let manifest = ClientEvidenceTransferManifest {
    format_version: CLIENT_EVIDENCE_FORMAT_VERSION,
    incident_id,
    maintenance_epoch,
    candidate,
    server_bundle_sha256,
    artifact_bytes_sha256,
    artifacts,
  };
  serde_yaml::to_string (&manifest)
    . map (|text| sha256_hex (text . as_bytes ()))
    . map_err (|error| error . to_string ())
}

fn validate_candidate_contract (
  active    : &ActiveMaintenance,
  config    : &SkgConfig,
  selected  : &SelectedStoreState,
  candidate : &ObservedDiskCandidate,
) -> Result<(), String> {
  let Some (expected) = &active . candidate else {
    return Err ("maintenance incident has no disk candidate" . into ()); };
  if expected != &candidate . summary {
    return Err ("maintenance incident does not name this exact candidate" . into ()); }
  if active . g0_graph_generation != selected . graph_generation
  || active . g0_manifest_revision != selected . manifest_revision
  || candidate . summary . base_graph_generation != selected . graph_generation
  || candidate . summary . base_manifest_revision != selected . manifest_revision
  {
    return Err ("candidate evidence does not share the active G0" . into ()); }
  if config_identity (config) != candidate . config_identity {
    return Err ("candidate evidence configuration identity changed" . into ()); }
  if config_file_blake3 (config) != candidate . config_file_blake3 {
    return Err ("candidate evidence configuration bytes changed" . into ()); }
  if source_catalog_blake3 (config) != candidate . source_catalog_blake3 {
    return Err ("candidate evidence source catalog changed" . into ()); }
  let byte_paths : BTreeSet<&PathBuf> = candidate . selected_bytes . keys () . collect ();
  match &candidate . disk_fence {
    crate::maintenance::candidate::CandidateDiskFence::Complete => {
      let candidate_paths : BTreeSet<&PathBuf> =
        candidate . manifest . keys () . collect ();
      if candidate_paths != byte_paths {
        return Err (
          "candidate selected-byte inventory is incomplete" . into ()); }
    }
    crate::maintenance::candidate::CandidateDiskFence::Targeted (fence) => {
      let possible_paths : BTreeSet<&PathBuf> = fence . keys () . collect ();
      let selected_target_paths : BTreeSet<&PathBuf> = candidate . manifest
        . keys () . filter (|path| possible_paths . contains (path)) . collect ();
      if byte_paths != selected_target_paths {
        return Err (
          "targeted candidate selected-byte inventory is incomplete"
            . into ()); }
    }
  }
  for (path, bytes) in &candidate . selected_bytes {
    if candidate . manifest . get (path)
       != Some (&crate::types::store_state::PathDigest::of_bytes (bytes))
    {
      return Err (format! (
        "candidate bytes do not match manifest at {}", path . display ())); }
  }
  Ok (( ))
}

fn build_bundle (
  active    : &ActiveMaintenance,
  config    : &SkgConfig,
  selected  : &SelectedStoreState,
  candidate : &ObservedDiskCandidate,
) -> Result<(MaintenanceEvidenceBundle, Vec<ArtifactBytes>), String> {
  let mut artifacts = Vec::new ();
  let classified : BTreeSet<&ID> = candidate . added_primary_ids . iter ()
    . chain (&candidate . deleted_primary_ids)
    . chain (&candidate . modified_primary_ids) . collect ();
  if classified != candidate . evidence . keys () . collect () {
    return Err ("candidate evidence/change classification differs" . into ()); }
  for (index, (pid, evidence)) in candidate . evidence . iter () . enumerate () {
    let (category, change) = change_category (candidate, pid)?;
    let directory = PathBuf::from (category) . join (format! (
      "node-{:08}-{}", index, &sha256_hex (pid . to_string () . as_bytes ())[..12]));
    let readme = format! (
      "* {} node\n- Primary ID :: {:?}\n- Evidence key :: {}\n\nThe exact authored source-path outcomes are in [[file:sources.sexp][sources.sexp]].\n",
      change, pid . to_string (), directory . display ());
    artifacts . push (artifact (
      directory . join ("README.org"), "node-readme", None,
      readme . into_bytes ()));
    if let Some (before) = &evidence . before {
      artifacts . push (artifact (
        directory . join ("before.semantic.yaml"), "semantic-before", None,
        serde_yaml::to_string (before)
          . map_err (|error| error . to_string ())? . into_bytes ())); }
    if let Some (after) = &evidence . after {
      artifacts . push (artifact (
        directory . join ("after.semantic.yaml"), "semantic-after", None,
        serde_yaml::to_string (after)
          . map_err (|error| error . to_string ())? . into_bytes ())); }
    artifacts . push (artifact (
      directory . join ("semantic.diff"), "semantic-diff", None,
      evidence . diff . as_bytes () . to_vec ()));
    let pid_text = pid . to_string ();
    let paths : BTreeSet<PathBuf> = selected . manifest . keys ()
      . chain (candidate . manifest . keys ())
      . filter (|path| path_primary_id (path) . as_deref ()
        == Some (pid_text . as_str ()))
      . cloned () . collect ();
    let mut source_records = Vec::new ();
    let mut raw_artifacts = Vec::new ();
    for (path_index, path) in paths . iter () . enumerate () {
      let path_hash = sha256_hex (path . to_string_lossy () . as_bytes ());
      let raw_relative = candidate . selected_bytes . get (path) . map (|bytes| {
        let relative = directory . join ("raw") . join (format! (
          "path-{:08}-{}.after.skg", path_index, &path_hash[..12]));
        raw_artifacts . push (artifact (
          relative . clone (), "raw-after", Some (path . clone ()),
          bytes . clone ()));
        relative . to_string_lossy () . to_string ()
      });
      source_records . push (source_record_sexp (
        path_index, path,
        selected . manifest . get (path) . map (|digest| digest . to_hex ()),
        candidate . manifest . get (path) . map (|digest| digest . to_hex ()),
        raw_relative . as_deref ()));
    }
    let sources = Sexp::List (vec![
      evidence_field ("format-version", "1"),
      evidence_field ("primary-id", &pid . to_string ()),
      Sexp::List (vec![
        Sexp::Atom (Atom::S ("paths" . into ())),
        Sexp::List (source_records),
      ]),
    ]) . to_string () . into_bytes ();
    artifacts . push (artifact (
      directory . join ("sources.sexp"), "source-outcomes", None, sources));
    artifacts . extend (raw_artifacts);
  }

  let mut g0_nodes : Vec<SemanticNodeEvidence> =
    nodecompletes_from_graph (&selected . graph) . iter ()
      . map (SemanticNodeEvidence::from) . collect ();
  let mut g1_nodes : Vec<SemanticNodeEvidence> =
    nodecompletes_from_graph (&candidate . graph) . iter ()
      . map (SemanticNodeEvidence::from) . collect ();
  g0_nodes . sort_by (|left, right| left . pid . cmp (&right . pid));
  g1_nodes . sort_by (|left, right| left . pid . cmp (&right . pid));
  let transition_delta = candidate . definitions . iter () . map (|definition|
    match definition {
      DefineNode::Save (SaveNode (node)) => EvidenceDefinition::Save {
        node: SemanticNodeEvidence::from (node),
      },
      DefineNode::Delete (DeleteNode { id, source }) => EvidenceDefinition::Delete {
        id: id . clone (), source: source . clone (),
      },
    }) . collect ();
  let bundle = MaintenanceEvidenceBundle {
    format_version: EVIDENCE_FORMAT_VERSION,
    incident_id: active . incident_id . clone (),
    maintenance_epoch: active . epoch,
    candidate: candidate . summary . clone (),
    config_identity: config_identity (config),
    config_file_blake3: config_file_blake3 (config),
    source_catalog_blake3: source_catalog_blake3 (config),
    g0_graph_generation: selected . graph_generation,
    g0_manifest_revision: selected . manifest_revision,
    g0_manifest: selected . manifest . clone (),
    g1_manifest: candidate . manifest . clone (),
    g0_nodes,
    g1_nodes,
    transition_delta,
    added_primary_ids: candidate . added_primary_ids . clone (),
    deleted_primary_ids: candidate . deleted_primary_ids . clone (),
    modified_primary_ids: candidate . modified_primary_ids . clone (),
    semantic_evidence: candidate . evidence . clone (),
    warnings: candidate . warnings . clone (),
    artifacts: Vec::new (),
  };
  Ok ((bundle, artifacts))
}

fn artifact (
  relative_path : PathBuf,
  purpose       : &str,
  source_path   : Option<PathBuf>,
  bytes         : Vec<u8>,
) -> ArtifactBytes {
  ArtifactBytes {
    metadata: EvidenceArtifact {
      relative_path,
      purpose: purpose . into (),
      source_path,
      byte_length: bytes . len () as u64,
      sha256: sha256_hex (&bytes),
      blake3: blake3_hex (&bytes),
    },
    bytes,
  }
}

fn change_category (
  candidate : &ObservedDiskCandidate,
  pid       : &ID,
) -> Result<(&'static str, &'static str), String> {
  if candidate . added_primary_ids . contains (pid) {
    Ok (("new-nodes", "Added"))
  } else if candidate . deleted_primary_ids . contains (pid) {
    Ok (("deleted-nodes", "Deleted"))
  } else if candidate . modified_primary_ids . contains (pid) {
    Ok (("modified-nodes", "Modified"))
  } else {
    Err (format! ("changed node {} has no classification", pid))
  }
}

fn path_primary_id (path : &Path) -> Option<String> {
  path . file_stem () . and_then (|stem| stem . to_str ())
    . map (str::to_string)
}

fn source_record_sexp (
  index         : usize,
  path          : &Path,
  before_blake3 : Option<String>,
  after_blake3  : Option<String>,
  raw_after     : Option<&str>,
) -> Sexp {
  Sexp::List (vec![
    evidence_field ("path-key", &format! ("path-{:08}", index)),
    evidence_field ("display-path", &path . to_string_lossy ()),
    evidence_field ("before-blake3",
      before_blake3 . as_deref () . unwrap_or ("absent")),
    evidence_field ("after-blake3",
      after_blake3 . as_deref () . unwrap_or ("absent")),
    evidence_field ("raw-before-artifact", "unavailable"),
    evidence_field ("raw-after-artifact", raw_after . unwrap_or ("absent")),
  ])
}

fn evidence_field (key : &str, value : &str) -> Sexp {
  Sexp::List (vec![
    Sexp::Atom (Atom::S (key . into ())),
    Sexp::Atom (Atom::S (value . into ())),
  ])
}

fn validate_evidence_directory (
  directory       : &Path,
  config_identity : &Path,
  incident        : Option<&IncidentId>,
) -> Result<(MaintenanceEvidenceBundle, PublishedMaintenanceEvidence), String> {
  require_private_directory (directory)?;
  let bundle_path = directory . join ("bundle.yaml");
  let bundle_bytes = fs::read (&bundle_path)
    . map_err (|error| format! ("could not read {}: {}",
      bundle_path . display (), error))?;
  require_private_regular_file (&bundle_path)?;
  let envelope : EvidenceEnvelope = serde_yaml::from_slice (&bundle_bytes)
    . map_err (|error| format! ("invalid evidence bundle: {}", error))?;
  if envelope . payload . format_version != EVIDENCE_FORMAT_VERSION {
    return Err (format! ("unsupported evidence bundle version {}",
      envelope . payload . format_version)); }
  if let Some (expected) = incident {
    if &envelope . payload . incident_id != expected {
      return Err ("evidence directory has the wrong incident ID" . into ()); }}
  if envelope . payload . config_identity != config_identity {
    return Err ("evidence bundle belongs to a different config" . into ()); }
  let payload_bytes = serde_yaml::to_string (&envelope . payload)
    . map_err (|error| error . to_string ())? . into_bytes ();
  if blake3_hex (&payload_bytes) != envelope . payload_blake3 {
    return Err ("evidence payload checksum mismatch" . into ()); }

  let mut expected_files : BTreeSet<PathBuf> =
    BTreeSet::from ([PathBuf::from ("bundle.yaml")]);
  let mut total_file_bytes = bundle_bytes . len () as u64;
  for artifact in &envelope . payload . artifacts {
    validate_relative_artifact_path (&artifact . relative_path)?;
    if !expected_files . insert (artifact . relative_path . clone ()) {
      return Err (format! ("duplicate evidence artifact {}",
        artifact . relative_path . display ())); }
    let path = directory . join (&artifact . relative_path);
    require_private_regular_file (&path)?;
    let bytes = fs::read (&path) . map_err (|error| error . to_string ())?;
    if bytes . len () as u64 != artifact . byte_length
    || sha256_hex (&bytes) != artifact . sha256
    || blake3_hex (&bytes) != artifact . blake3
    {
      return Err (format! ("evidence artifact checksum mismatch at {}",
        artifact . relative_path . display ())); }
    total_file_bytes += bytes . len () as u64;
  }
  let actual_files = regular_file_inventory (directory)?;
  if actual_files != expected_files {
    return Err (format! (
      "evidence file inventory mismatch: expected {:?}, found {:?}",
      expected_files, actual_files)); }
  Ok ((envelope . payload, PublishedMaintenanceEvidence {
    path: directory . to_path_buf (),
    bundle_sha256: sha256_hex (&bundle_bytes),
    artifact_count: expected_files . len () - 1,
    total_file_bytes,
  }))
}

fn regular_file_inventory (root : &Path) -> Result<BTreeSet<PathBuf>, String> {
  let mut files = BTreeSet::new ();
  for entry in walkdir::WalkDir::new (root) . follow_links (false) {
    let entry = entry . map_err (|error| error . to_string ())?;
    if entry . path () == root { continue; }
    let metadata = fs::symlink_metadata (entry . path ())
      . map_err (|error| error . to_string ())?;
    if metadata . file_type () . is_symlink () {
      return Err (format! ("symlink is forbidden in evidence: {}",
        entry . path () . display ())); }
    if metadata . is_dir () {
      require_private_directory (entry . path ())?;
    } else if metadata . is_file () {
      require_private_regular_file (entry . path ())?;
      files . insert (entry . path () . strip_prefix (root)
        . map_err (|error| error . to_string ())? . to_path_buf ());
    } else {
      return Err (format! ("special file is forbidden in evidence: {}",
        entry . path () . display ())); }
  }
  Ok (files)
}

fn validate_relative_artifact_path (path : &Path) -> Result<(), String> {
  if path . is_absolute () || path . components () . any (|component|
      !matches! (component, std::path::Component::Normal (_)))
  {
    return Err (format! ("unsafe evidence artifact path {}", path . display ())); }
  if path == Path::new ("bundle.yaml") {
    return Err ("artifact may not replace bundle.yaml" . into ()); }
  Ok (( ))
}

fn write_private_file (path : &Path, bytes : &[u8]) -> Result<(), String> {
  let mut options = OpenOptions::new ();
  options . write (true) . create_new (true);
  #[cfg(unix)]
  options . mode (0o600);
  let mut file = options . open (path) . map_err (|error| format! (
    "could not create {}: {}", path . display (), error))?;
  file . write_all (bytes) . map_err (|error| error . to_string ())?;
  file . sync_all () . map_err (|error| error . to_string ())?;
  drop (file);
  Ok (( ))
}

fn create_private_directory (path : &Path) -> Result<(), String> {
  let mut builder = fs::DirBuilder::new ();
  #[cfg(unix)]
  builder . mode (0o700);
  builder . create (path) . map_err (|error| format! (
    "could not create {}: {}", path . display (), error))
}

fn create_private_directory_all (path : &Path) -> Result<(), String> {
  if fs::symlink_metadata (path) . is_ok () {
    return require_private_directory (path); }
  let mut missing = Vec::new ();
  let mut cursor = path;
  while fs::symlink_metadata (cursor) . is_err () {
    missing . push (cursor . to_path_buf ());
    cursor = cursor . parent ()
      . ok_or_else (|| format! ("directory has no existing parent: {}",
        path . display ()))?;
  }
  for directory in missing . into_iter () . rev () {
    match create_private_directory (&directory) {
      Ok (( )) => {},
      Err (_) if fs::symlink_metadata (&directory) . is_ok () =>
        require_private_directory (&directory)?,
      Err (error) => return Err (error),
    }
  }
  Ok (( ))
}

fn require_private_directory (path : &Path) -> Result<(), String> {
  let metadata = fs::symlink_metadata (path) . map_err (|error| format! (
    "could not inspect {}: {}", path . display (), error))?;
  if metadata . file_type () . is_symlink () || !metadata . is_dir () {
    return Err (format! ("evidence path is not a real directory: {}",
      path . display ())); }
  #[cfg(unix)]
  if metadata . permissions () . mode () & 0o777 != 0o700 {
    return Err (format! ("evidence directory is not mode 0700: {}",
      path . display ())); }
  Ok (( ))
}

fn require_private_regular_file (path : &Path) -> Result<(), String> {
  let metadata = fs::symlink_metadata (path) . map_err (|error| format! (
    "could not inspect {}: {}", path . display (), error))?;
  if metadata . file_type () . is_symlink () || !metadata . is_file () {
    return Err (format! ("evidence artifact is not a regular file: {}",
      path . display ())); }
  #[cfg(unix)]
  {
    if metadata . permissions () . mode () & 0o777 != 0o600 {
      return Err (format! ("evidence artifact is not mode 0600: {}",
        path . display ())); }
    if metadata . nlink () != 1 {
      return Err (format! ("evidence artifact is hard-linked: {}",
        path . display ())); }
  }
  Ok (( ))
}

fn sync_tree_directories (root : &Path) -> Result<(), String> {
  let mut directories : Vec<PathBuf> = walkdir::WalkDir::new (root)
    . follow_links (false) . into_iter () . filter_map (Result::ok)
    .filter (|entry| entry . file_type () . is_dir ())
    .map (|entry| entry . into_path ()) . collect ();
  directories . sort_by_key (|path| std::cmp::Reverse (path . components () . count ()));
  for directory in directories { sync_directory (&directory)?; }
  Ok (( ))
}

fn sync_directory (path : &Path) -> Result<(), String> {
  #[cfg(unix)]
  {
    let mut directory = File::open (path) . map_err (|error| error . to_string ())?;
    let mut byte = [0u8; 0];
    directory . read (&mut byte) . ok ();
    directory . sync_all () . map_err (|error| error . to_string ())?;
  }
  Ok (( ))
}

fn sha256_hex (bytes : &[u8]) -> String {
  format! ("{:x}", Sha256::digest (bytes))
}

fn blake3_hex (bytes : &[u8]) -> String {
  blake3::hash (bytes) . to_hex () . to_string ()
}

#[cfg(test)]
mod tests {
  use super::*;
  use crate::dbs::in_rust_graph::InRustGraph;
  use crate::maintenance::{
    CandidateId,
    MaintenanceCoordinator,
    MaintenanceOrigin,
    ObservationSequence,
  };
  use crate::types::misc::SkgConfig;
  use crate::types::store_state::{PathDigest, SelectedStoreState};
  use std::sync::Arc;
  use tempfile::tempdir;

  #[test]
  fn rejects_undeclared_and_nonprivate_artifacts () {
    let temporary = tempdir () . unwrap ();
    let root = temporary . path () . join ("evidence");
    let store = MaintenanceEvidenceStore::at_root (
      root . clone (), PathBuf::from ("/config"));
    create_private_directory_all (&root) . unwrap ();
    let incident = IncidentId::new ();
    let directory = root . join (incident . as_str ());
    create_private_directory (&directory) . unwrap ();
    write_private_file (&directory . join ("undeclared"), b"x") . unwrap ();
    assert! (store . load (&incident) . is_err ());
  }

  #[test]
  fn relative_artifact_paths_cannot_escape () {
    assert! (validate_relative_artifact_path (Path::new ("bytes/1.bin")) . is_ok ());
    assert! (validate_relative_artifact_path (Path::new ("../outside")) . is_err ());
    assert! (validate_relative_artifact_path (Path::new ("/outside")) . is_err ());
  }

  #[test]
  fn candidate_bundle_round_trips_and_rejects_an_extra_file () {
    let temporary = tempdir () . unwrap ();
    let config_path = temporary . path () . join ("skgconfig.toml");
    fs::write (&config_path, b"") . unwrap ();
    let mut config = SkgConfig::dummyFromSources (Default::default ());
    config . config_path = config_path . clone ();
    let selected = SelectedStoreState::initial (
      InRustGraph::new (), Default::default ());
    let summary = CandidateSummary {
      id: CandidateId::new (),
      base_graph_generation: selected . graph_generation,
      base_manifest_revision: selected . manifest_revision,
      covered_sequence: ObservationSequence::INITIAL,
      changed_primary_ids: Vec::new (),
    };
    let candidate = ObservedDiskCandidate {
      summary: summary . clone (),
      config_identity: config_identity (&config),
      config_file_blake3:
        crate::maintenance::candidate::config_file_blake3 (&config),
      source_catalog_blake3: source_catalog_blake3 (&config),
      config: Arc::new (config . clone ()),
      manifest: Default::default (),
      base_graph: Arc::new (InRustGraph::new ()),
      graph: Arc::new (InRustGraph::new ()),
      definitions: Vec::new (),
      added_primary_ids: Default::default (),
      deleted_primary_ids: Default::default (),
      modified_primary_ids: Default::default (),
      evidence: Default::default (),
      selected_bytes: Default::default (),
      warnings: Vec::new (),
      load_violations: Vec::new (),
      disk_fence: crate::maintenance::candidate::CandidateDiskFence::Complete,
    };
    let mut coordinator = MaintenanceCoordinator::new ();
    let active = coordinator . begin (
      MaintenanceOrigin::PendingReconciliation, Some (summary)) . unwrap ();
    let store = MaintenanceEvidenceStore::at_root (
      temporary . path () . join ("evidence"), config_identity (&config));
    let publication = store . publish_candidate (
      &active, &config, &selected, &candidate) . unwrap ();
    let (loaded, loaded_publication) = store . load (&active . incident_id) . unwrap ();
    assert_eq! (loaded . candidate, candidate . summary);
    assert_eq! (loaded_publication, publication);
    let client = store . client_bundle (&active . incident_id) . unwrap ();
    assert! (client . artifacts . is_empty ());
    assert! (client . bytes . is_empty ());
    assert_eq! (client . artifact_bytes_sha256, sha256_hex (&[]));
    let mut replacement_candidate = candidate . clone ();
    replacement_candidate . summary . id = CandidateId::new ();
    let mut replacement_active = active . clone ();
    replacement_active . candidate = Some (
      replacement_candidate . summary . clone ());
    let replacement_publication = store . publish_candidate (
      &replacement_active, &config, &selected, &replacement_candidate)
      . unwrap ();
    assert_eq! (store . load (&active . incident_id) . unwrap () . 0
      . candidate, replacement_candidate . summary);
    let preserved_prefix = format! (
      "{}--superseded--{}--", active . incident_id, candidate . summary . id);
    assert! (fs::read_dir (&store . directory) . unwrap ()
      . filter_map (Result::ok) . any (|entry| entry . file_name ()
        . to_string_lossy () . starts_with (&preserved_prefix)));
    write_private_file (
      &replacement_publication . path . join ("extra"), b"no") . unwrap ();
    assert! (store . load (&active . incident_id) . is_err ());
  }

  #[test]
  fn client_bundle_uses_safe_final_paths_and_exact_ordered_slices () {
    let temporary = tempdir () . unwrap ();
    let config_path = temporary . path () . join ("skgconfig.toml");
    fs::write (&config_path, b"") . unwrap ();
    let mut config = SkgConfig::dummyFromSources (Default::default ());
    config . config_path = config_path;
    let pid = ID::from ("node one");
    let path = temporary . path () . join ("node one.skg");
    let before_bytes = b"before telescope\n";
    let after_bytes = vec![0xff, 0xfe, b'\n'];
    let selected = SelectedStoreState::initial (
      InRustGraph::new (), BTreeMap::from ([
        (path . clone (), PathDigest::of_bytes (before_bytes)),
      ]));
    let summary = CandidateSummary {
      id: CandidateId::new (),
      base_graph_generation: selected . graph_generation,
      base_manifest_revision: selected . manifest_revision,
      covered_sequence: ObservationSequence::INITIAL,
      changed_primary_ids: vec![pid . to_string ()],
    };
    let before = semantic_node (&pid, "before");
    let after = semantic_node (&pid, "after");
    let candidate = ObservedDiskCandidate {
      summary: summary . clone (),
      config_identity: config_identity (&config),
      config_file_blake3:
        crate::maintenance::candidate::config_file_blake3 (&config),
      source_catalog_blake3: source_catalog_blake3 (&config),
      config: Arc::new (config . clone ()),
      manifest: BTreeMap::from ([
        (path . clone (), PathDigest::of_bytes (&after_bytes)),
      ]),
      base_graph: Arc::new (InRustGraph::new ()),
      graph: Arc::new (InRustGraph::new ()),
      definitions: Vec::new (),
      added_primary_ids: Default::default (),
      deleted_primary_ids: Default::default (),
      modified_primary_ids: BTreeSet::from ([pid . clone ()]),
      evidence: BTreeMap::from ([
        (pid . clone (), SemanticChangeEvidence {
          before: Some (before), after: Some (after),
          diff: "-before\n+after\n" . into (),
        }),
      ]),
      selected_bytes: BTreeMap::from ([(path, after_bytes . clone ())]),
      warnings: Vec::new (),
      load_violations: Vec::new (),
      disk_fence: crate::maintenance::candidate::CandidateDiskFence::Complete,
    };
    let mut coordinator = MaintenanceCoordinator::new ();
    let active = coordinator . begin (
      MaintenanceOrigin::PendingReconciliation, Some (summary)) . unwrap ();
    let store = MaintenanceEvidenceStore::at_root (
      temporary . path () . join ("evidence"), config_identity (&config));
    let publication = store . publish_candidate (
      &active, &config, &selected, &candidate) . unwrap ();
    let client = store . client_bundle (&active . incident_id) . unwrap ();
    assert_eq! (store . client_bundle (&active . incident_id) . unwrap (), client);

    assert_eq! (client . artifacts . len (), publication . artifact_count);
    assert! (client . artifacts . iter () . all (|record|
      record . relative_path . starts_with (
        "modified-nodes/node-00000000-")
      && !record . relative_path . contains ("..")));
    let mut expected_offset = 0;
    for record in &client . artifacts {
      assert_eq! (record . byte_offset, expected_offset);
      let start = record . byte_offset as usize;
      let end = start + record . byte_length as usize;
      assert_eq! (sha256_hex (&client . bytes[start..end]), record . sha256);
      expected_offset += record . byte_length;
    }
    let raw = client . artifacts . iter ()
      . find (|record| record . purpose == "raw-after") . unwrap ();
    let start = raw . byte_offset as usize;
    let end = start + raw . byte_length as usize;
    assert_eq! (&client . bytes[start..end], after_bytes);
  }

  fn semantic_node (pid : &ID, title : &str) -> SemanticNodeEvidence {
    SemanticNodeEvidence {
      format_version: 1,
      pid: pid . to_string (),
      source: "source" . into (),
      title: title . into (),
      ugly_telescope: false,
      extra_ids: Vec::new (),
      body: None,
      aliases: None,
      contains: Vec::new (),
      subscribes_to: None,
      hides_from_its_subscriptions: None,
      overrides_view_of: None,
      file_properties: Vec::new (),
    }
  }
}
