//! Durable, process-owned evidence published before candidate selection.
//!
//! The client archive proves that editor state is recoverable.  This bundle
//! proves what the server is about to do to the derived stores and gives a
//! restarted process immutable G0/G1 reconstruction inputs.  It is published
//! as one private directory rename before the first store mutation.

use super::candidate::{
  ObservedDiskCandidate,
  SemanticNodeEvidence,
  config_file_blake3,
  config_identity,
  source_catalog_blake3,
};
use super::journal::MaintenanceJournalStore;
use super::types::{ActiveMaintenance, CandidateSummary, IncidentId, MaintenanceEpoch};
use crate::save::nodecompletes_from_graph;
use crate::types::misc::{ID, SkgConfig};
use crate::types::store_state::{
  GraphGeneration,
  ManifestRevision,
  PathDigest,
  SelectedPathManifest,
  SelectedStoreState,
};

use serde::{Deserialize, Serialize};
use sexp::{Atom, Sexp};
use sha2::{Digest, Sha256};
use std::collections::{BTreeMap, BTreeSet};
use std::fs::{self, File, OpenOptions};
use std::io::{Cursor, Read, Write};
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex};

#[cfg(unix)]
use std::os::unix::fs::{
  DirBuilderExt,
  MetadataExt,
  OpenOptionsExt,
  PermissionsExt,
};

const EVIDENCE_FORMAT_VERSION : u32 = 3;
const HEADER_FILENAME : &str = "header.yaml";
const RECOVERY_FILENAME : &str = "recovery.cbor.zst";
const RECOVERY_ENCODING : &str = "cbor";
const RECOVERY_COMPRESSION : &str = "zstd-level-3";
pub const CLIENT_EVIDENCE_FORMAT_VERSION : u32 = 1;

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct MaintenanceEvidenceHeader {
  pub format_version       : u32,
  pub incident_id          : IncidentId,
  pub maintenance_epoch    : MaintenanceEpoch,
  pub candidate             : CandidateSummary,
  pub config_identity       : PathBuf,
  pub config_file_blake3    : String,
  pub source_catalog_blake3 : String,
  pub g0_graph_generation   : GraphGeneration,
  pub g0_manifest_revision  : ManifestRevision,
  pub recovery              : RecoveryPayloadRecord,
  pub added_primary_ids     : BTreeSet<ID>,
  pub deleted_primary_ids   : BTreeSet<ID>,
  pub modified_primary_ids  : BTreeSet<ID>,
  pub warnings              : Vec<String>,
  pub artifacts             : Vec<EvidenceArtifact>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct RecoveryPayloadRecord {
  pub relative_path     : PathBuf,
  pub encoding          : String,
  pub compression       : String,
  pub uncompressed_bytes : u64,
  pub byte_length       : u64,
  pub sha256            : String,
  pub blake3            : String,
}

/// The one corpus-sized recovery value.  G1 is represented reversibly instead
/// of storing a second almost-identical corpus.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct MaintenanceRecoveryPayload {
  pub format_version : u32,
  pub g0_manifest           : SelectedPathManifest,
  pub g0_nodes              : Vec<SemanticNodeEvidence>,
  pub node_delta            : Vec<ReversibleNodeDelta>,
  pub path_delta            : Vec<ReversiblePathDelta>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct ReversibleNodeDelta {
  pub primary_id : String,
  pub before     : Option<SemanticNodeEvidence>,
  pub after      : Option<SemanticNodeEvidence>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct ReversiblePathDelta {
  pub path   : PathBuf,
  pub before : Option<PathDigest>,
  pub after  : Option<PathDigest>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ReconstructedEvidence {
  pub g0_manifest : SelectedPathManifest,
  pub g1_manifest : SelectedPathManifest,
  pub g0_nodes    : BTreeMap<String, SemanticNodeEvidence>,
  pub g1_nodes    : BTreeMap<String, SemanticNodeEvidence>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct EvidenceArtifact {
  pub relative_path : PathBuf,
  pub purpose       : String,
  pub source_path   : Option<PathBuf>,
  pub byte_length   : u64,
  pub sha256        : String,
  pub blake3        : String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MaintenanceEvidenceBundle {
  pub header   : MaintenanceEvidenceHeader,
  pub recovery : MaintenanceRecoveryPayload,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PublishedMaintenanceEvidence {
  pub path             : PathBuf,
  pub bundle_sha256    : String,
  pub artifact_count   : usize,
  pub total_file_bytes : u64,
}

/// One exact slice in the opaque payload sent to the client.  Relative paths
/// are generated by the server and contain only safe components; source paths
/// remain content inside the corresponding `sources.sexp` artifact.
#[derive(Clone, Debug, Eq, PartialEq, Serialize)]
pub struct ClientEvidenceArtifact {
  pub key           : String,
  pub relative_path : String,
  pub purpose       : String,
  pub byte_offset   : u64,
  pub byte_length   : u64,
  pub sha256        : String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ClientEvidenceBundle {
  pub incident_id       : IncidentId,
  pub maintenance_epoch : MaintenanceEpoch,
  pub candidate          : CandidateSummary,
  pub server_bundle_sha256 : String,
  pub transfer_manifest_sha256 : String,
  pub artifact_bytes_sha256 : String,
  pub artifacts          : Vec<ClientEvidenceArtifact>,
  pub bytes              : Vec<u8>,
}

#[derive(Clone, Debug)]
pub struct MaintenanceEvidenceStore {
  directory       : PathBuf,
  config_identity : PathBuf,
  published       : Arc<Mutex<BTreeMap<IncidentId, CachedPublishedEvidence>>>,
}

#[derive(Clone, Debug)]
struct CachedPublishedEvidence {
  header      : MaintenanceEvidenceHeader,
  publication : PublishedMaintenanceEvidence,
}

struct ArtifactBytes {
  metadata : EvidenceArtifact,
  bytes    : Vec<u8>,
}

impl MaintenanceEvidenceStore {
  pub fn alongside (journal : &MaintenanceJournalStore) -> Self {
    Self {
      directory: journal . directory () . join ("evidence"),
      config_identity: journal . config_identity () . to_path_buf (),
      published: Arc::new (Mutex::new (BTreeMap::new ())),
    }
  }

  #[cfg(test)]
  fn at_root (directory : PathBuf, config_identity : PathBuf) -> Self {
    Self {
      directory,
      config_identity,
      published: Arc::new (Mutex::new (BTreeMap::new ())),
    }
  }

  pub fn publish_candidate (
    &self,
    active    : &ActiveMaintenance,
    config    : &SkgConfig,
    selected  : &SelectedStoreState,
    candidate : &ObservedDiskCandidate,
  ) -> Result<PublishedMaintenanceEvidence, String> {
    validate_candidate_contract (active, config, selected, candidate)?;
    create_private_directory_all (&self . directory)?;
    let final_path = self . directory . join (active . incident_id . as_str ());
    if final_path . exists () {
      let (bundle, publication) = self . load (&active . incident_id)?;
      if bundle . header . candidate == candidate . summary {
        return Ok (publication); }
      // A candidate can become stale after its bundle is durable but before
      // the first store mutation.  Preserve that attempted evidence under a
      // unique sibling and free the canonical incident path for the exact
      // replacement candidate.  Nothing is deleted or overwritten.
      let superseded_path = self . directory . join (format! (
        "{}--superseded--{}--{}",
        active . incident_id, bundle . header . candidate . id,
        uuid::Uuid::new_v4 ()));
      fs::rename (&final_path, &superseded_path)
        . map_err (|error| format! (
          "could not preserve superseded candidate evidence: {}", error))?;
      self . forget_publication (&active . incident_id)?;
      sync_directory (&self . directory)?;
    }

    let temporary = self . directory . join (format! (
      ".{}.{}.tmp", active . incident_id, uuid::Uuid::new_v4 ()));
    create_private_directory (&temporary)?;
    let result = (|| {
      let (mut header, recovery, artifacts) = build_evidence (
        active, config, selected, candidate)?;
      for artifact in &artifacts {
        let path = temporary . join (&artifact . metadata . relative_path);
        let parent = path . parent ()
          . ok_or_else (|| "evidence artifact has no parent" . to_string ())?;
        create_private_directory_all (parent)?;
        write_private_file (&path, &artifact . bytes)?;
      }
      header . artifacts = artifacts . iter ()
        . map (|artifact| artifact . metadata . clone ()) . collect ();
      let recovery_uncompressed = encode_recovery_payload (&recovery)?;
      let recovery_bytes = zstd::stream::encode_all (
        Cursor::new (&recovery_uncompressed), 3)
        . map_err (|error| format! ("could not compress recovery evidence: {}",
          error))?;
      header . recovery = recovery_record (
        recovery_uncompressed . len (), &recovery_bytes);
      let header_bytes = serde_yaml::to_string (&header)
        . map_err (|error| error . to_string ())? . into_bytes ();
      write_private_file (
        &temporary . join (RECOVERY_FILENAME), &recovery_bytes)?;
      write_private_file (&temporary . join (HEADER_FILENAME), &header_bytes)?;
      sync_tree_directories (&temporary)?;
      let publication = verify_new_publication (
        &temporary, &header, &header_bytes, &recovery_bytes, &artifacts)?;
      fs::rename (&temporary, &final_path)
        . map_err (|error| error . to_string ())?;
      sync_directory (&self . directory)?;
      let publication = PublishedMaintenanceEvidence {
        path: final_path . clone (),
        .. publication
      };
      self . remember_publication (header, publication . clone ())?;
      Ok (publication)
    })();
    // Incomplete temporary directories are intentionally retained.  They are
    // crash evidence and, unlike the final path, never grant mutation authority.
    result
  }

  pub fn load (
    &self,
    incident : &IncidentId,
  ) -> Result<(MaintenanceEvidenceBundle, PublishedMaintenanceEvidence), String> {
    let result = load_evidence_directory (
      &self . directory . join (incident . as_str ()),
      &self . config_identity,
      Some (incident))?;
    self . remember_publication (
      result . 0 . header . clone (), result . 1 . clone ())?;
    Ok (result)
  }

  /// Re-read the already-published evidence and concatenate its declared
  /// client artifacts in manifest order.  Every slice is rechecked after the
  /// read, so a replay never transmits bytes under an obsolete checksum.
  pub fn client_bundle (
    &self,
    incident : &IncidentId,
  ) -> Result<ClientEvidenceBundle, String> {
    let cached = self . published . lock ()
      . map_err (|_| "maintenance evidence cache was poisoned" . to_string ())?
      . get (incident) . cloned ();
    let (header, publication) = if let Some (cached) = cached {
      validate_cached_publication (&cached)?;
      (cached . header, cached . publication)
    } else {
      let (header, publication, _) = load_evidence_header (
        &self . directory . join (incident . as_str ()),
        &self . config_identity,
        Some (incident), true)?;
      self . remember_publication (header . clone (), publication . clone ())?;
      (header, publication)
    };
    let mut bytes = Vec::new ();
    let mut records = Vec::new ();
    for (index, artifact) in header . artifacts . iter () . enumerate () {
      let relative_path = artifact . relative_path . to_str ()
        . ok_or_else (|| "client evidence path is not UTF-8" . to_string ())?
        . to_string ();
      let artifact_bytes = validate_artifact_bytes (
        &publication . path, artifact) . map_err (|error| format! (
          "evidence artifact changed before transfer: {}: {}",
          relative_path, error))?;
      let byte_offset = bytes . len () as u64;
      bytes . extend_from_slice (&artifact_bytes);
      records . push (ClientEvidenceArtifact {
        key: format! ("artifact-{:08}", index),
        relative_path,
        purpose: artifact . purpose . clone (),
        byte_offset,
        byte_length: artifact . byte_length,
        sha256: artifact . sha256 . clone (),
      });
    }
    let artifact_bytes_sha256 = sha256_hex (&bytes);
    let transfer_manifest_sha256 = client_transfer_manifest_sha256 (
      &header . incident_id, header . maintenance_epoch, &header . candidate,
      &publication . bundle_sha256, &artifact_bytes_sha256, &records)?;
    Ok (ClientEvidenceBundle {
      incident_id: header . incident_id,
      maintenance_epoch: header . maintenance_epoch,
      candidate: header . candidate,
      server_bundle_sha256: publication . bundle_sha256,
      transfer_manifest_sha256,
      artifact_bytes_sha256,
      artifacts: records,
      bytes,
    })
  }

  fn remember_publication (
    &self,
    header      : MaintenanceEvidenceHeader,
    publication : PublishedMaintenanceEvidence,
  ) -> Result<(), String> {
    self . published . lock ()
      . map_err (|_| "maintenance evidence cache was poisoned" . to_string ())?
      . insert (header . incident_id . clone (), CachedPublishedEvidence {
        header,
        publication,
      });
    Ok (( ))
  }

  fn forget_publication (&self, incident : &IncidentId) -> Result<(), String> {
    self . published . lock ()
      . map_err (|_| "maintenance evidence cache was poisoned" . to_string ())?
      . remove (incident);
    Ok (( ))
  }
}

#[derive(Serialize)]
struct ClientEvidenceTransferManifest<'a> {
  format_version        : u32,
  incident_id           : &'a IncidentId,
  maintenance_epoch     : MaintenanceEpoch,
  candidate             : &'a CandidateSummary,
  server_bundle_sha256  : &'a str,
  artifact_bytes_sha256 : &'a str,
  artifacts             : &'a [ClientEvidenceArtifact],
}

fn client_transfer_manifest_sha256 (
  incident_id           : &IncidentId,
  maintenance_epoch     : MaintenanceEpoch,
  candidate             : &CandidateSummary,
  server_bundle_sha256  : &str,
  artifact_bytes_sha256 : &str,
  artifacts             : &[ClientEvidenceArtifact],
) -> Result<String, String> {
  let manifest = ClientEvidenceTransferManifest {
    format_version: CLIENT_EVIDENCE_FORMAT_VERSION,
    incident_id,
    maintenance_epoch,
    candidate,
    server_bundle_sha256,
    artifact_bytes_sha256,
    artifacts,
  };
  serde_yaml::to_string (&manifest)
    . map (|text| sha256_hex (text . as_bytes ()))
    . map_err (|error| error . to_string ())
}

fn validate_candidate_contract (
  active    : &ActiveMaintenance,
  config    : &SkgConfig,
  selected  : &SelectedStoreState,
  candidate : &ObservedDiskCandidate,
) -> Result<(), String> {
  let Some (expected) = &active . candidate else {
    return Err ("maintenance incident has no disk candidate" . into ()); };
  if expected != &candidate . summary {
    return Err ("maintenance incident does not name this exact candidate" . into ()); }
  if active . g0_graph_generation != selected . graph_generation
  || active . g0_manifest_revision != selected . manifest_revision
  || candidate . summary . base_graph_generation != selected . graph_generation
  || candidate . summary . base_manifest_revision != selected . manifest_revision
  {
    return Err ("candidate evidence does not share the active G0" . into ()); }
  if config_identity (config) != candidate . config_identity {
    return Err ("candidate evidence configuration identity changed" . into ()); }
  if config_file_blake3 (config) != candidate . config_file_blake3 {
    return Err ("candidate evidence configuration bytes changed" . into ()); }
  if source_catalog_blake3 (config) != candidate . source_catalog_blake3 {
    return Err ("candidate evidence source catalog changed" . into ()); }
  let byte_paths : BTreeSet<&PathBuf> = candidate . selected_bytes . keys () . collect ();
  match &candidate . disk_fence {
    crate::maintenance::candidate::CandidateDiskFence::Complete => {
      let candidate_paths : BTreeSet<&PathBuf> =
        candidate . manifest . keys () . collect ();
      if candidate_paths != byte_paths {
        return Err (
          "candidate selected-byte inventory is incomplete" . into ()); }
    }
    crate::maintenance::candidate::CandidateDiskFence::Targeted (fence) => {
      let possible_paths : BTreeSet<&PathBuf> = fence . keys () . collect ();
      let selected_target_paths : BTreeSet<&PathBuf> = candidate . manifest
        . keys () . filter (|path| possible_paths . contains (path)) . collect ();
      if byte_paths != selected_target_paths {
        return Err (
          "targeted candidate selected-byte inventory is incomplete"
            . into ()); }
    }
  }
  for (path, bytes) in &candidate . selected_bytes {
    if candidate . manifest . get (path)
       != Some (&crate::types::store_state::PathDigest::of_bytes (bytes))
    {
      return Err (format! (
        "candidate bytes do not match manifest at {}", path . display ())); }
  }
  Ok (( ))
}

fn build_evidence (
  active    : &ActiveMaintenance,
  config    : &SkgConfig,
  selected  : &SelectedStoreState,
  candidate : &ObservedDiskCandidate,
) -> Result<(
  MaintenanceEvidenceHeader,
  MaintenanceRecoveryPayload,
  Vec<ArtifactBytes>,
), String> {
  let mut artifacts = Vec::new ();
  let classified : BTreeSet<&ID> = candidate . added_primary_ids . iter ()
    . chain (&candidate . deleted_primary_ids)
    . chain (&candidate . modified_primary_ids) . collect ();
  if classified != candidate . evidence . keys () . collect () {
    return Err ("candidate evidence/change classification differs" . into ()); }
  for (index, (pid, evidence)) in candidate . evidence . iter () . enumerate () {
    let (category, change) = change_category (candidate, pid)?;
    let directory = PathBuf::from (category) . join (format! (
      "node-{:08}-{}", index, &sha256_hex (pid . to_string () . as_bytes ())[..12]));
    let readme = format! (
      "* {} node\n- Primary ID :: {:?}\n- Evidence key :: {}\n\nThe exact authored source-path outcomes are in [[file:sources.sexp][sources.sexp]].\n",
      change, pid . to_string (), directory . display ());
    artifacts . push (artifact (
      directory . join ("README.org"), "node-readme", None,
      readme . into_bytes ()));
    if let Some (before) = &evidence . before {
      artifacts . push (artifact (
        directory . join ("before.semantic.yaml"), "semantic-before", None,
        serde_yaml::to_string (before)
          . map_err (|error| error . to_string ())? . into_bytes ())); }
    if let Some (after) = &evidence . after {
      artifacts . push (artifact (
        directory . join ("after.semantic.yaml"), "semantic-after", None,
        serde_yaml::to_string (after)
          . map_err (|error| error . to_string ())? . into_bytes ())); }
    artifacts . push (artifact (
      directory . join ("semantic.diff"), "semantic-diff", None,
      evidence . diff . as_bytes () . to_vec ()));
    let pid_text = pid . to_string ();
    let paths : BTreeSet<PathBuf> = selected . manifest . keys ()
      . chain (candidate . manifest . keys ())
      . filter (|path| path_primary_id (path) . as_deref ()
        == Some (pid_text . as_str ()))
      . cloned () . collect ();
    let mut source_records = Vec::new ();
    let mut raw_artifacts = Vec::new ();
    for (path_index, path) in paths . iter () . enumerate () {
      let path_hash = sha256_hex (path . to_string_lossy () . as_bytes ());
      let raw_relative = candidate . selected_bytes . get (path) . map (|bytes| {
        let relative = directory . join ("raw") . join (format! (
          "path-{:08}-{}.after.skg", path_index, &path_hash[..12]));
        raw_artifacts . push (artifact (
          relative . clone (), "raw-after", Some (path . clone ()),
          bytes . clone ()));
        relative . to_string_lossy () . to_string ()
      });
      source_records . push (source_record_sexp (
        path_index, path,
        selected . manifest . get (path) . map (|digest| digest . to_hex ()),
        candidate . manifest . get (path) . map (|digest| digest . to_hex ()),
        raw_relative . as_deref ()));
    }
    let sources = Sexp::List (vec![
      evidence_field ("format-version", "1"),
      evidence_field ("primary-id", &pid . to_string ()),
      Sexp::List (vec![
        Sexp::Atom (Atom::S ("paths" . into ())),
        Sexp::List (source_records),
      ]),
    ]) . to_string () . into_bytes ();
    artifacts . push (artifact (
      directory . join ("sources.sexp"), "source-outcomes", None, sources));
    artifacts . extend (raw_artifacts);
  }

  let mut g0_nodes : Vec<SemanticNodeEvidence> =
    nodecompletes_from_graph (&selected . graph) . iter ()
      . map (SemanticNodeEvidence::from) . collect ();
  g0_nodes . sort_by (|left, right| left . pid . cmp (&right . pid));
  let node_delta = candidate . evidence . iter () . map (|(pid, evidence)|
    ReversibleNodeDelta {
      primary_id: pid . to_string (),
      before: evidence . before . clone (),
      after: evidence . after . clone (),
    }) . collect ();
  let all_paths : BTreeSet<PathBuf> = selected . manifest . keys () . cloned ()
    . chain (candidate . manifest . keys () . cloned ()) . collect ();
  let path_delta = all_paths . into_iter () . filter_map (|path| {
    let before = selected . manifest . get (&path) . copied ();
    let after = candidate . manifest . get (&path) . copied ();
    (before != after) . then_some (ReversiblePathDelta {
      path, before, after,
    })
  }) . collect ();
  let recovery = MaintenanceRecoveryPayload {
    format_version: EVIDENCE_FORMAT_VERSION,
    g0_manifest: (*selected . manifest) . clone (),
    g0_nodes,
    node_delta,
    path_delta,
  };
  let reconstructed = reconstruct_evidence (&recovery)?;
  if reconstructed . g1_manifest != candidate . manifest {
    return Err ("recovery path delta does not reconstruct candidate G1"
      . into ()); }
  let expected_g1_nodes : BTreeMap<String, SemanticNodeEvidence> =
    nodecompletes_from_graph (&candidate . graph) . iter ()
      . map (SemanticNodeEvidence::from)
      . map (|node| (node . pid . clone (), node))
      . collect ();
  if reconstructed . g1_nodes != expected_g1_nodes {
    return Err ("recovery node delta does not reconstruct candidate G1"
      . into ()); }
  let header = MaintenanceEvidenceHeader {
    format_version: EVIDENCE_FORMAT_VERSION,
    incident_id: active . incident_id . clone (),
    maintenance_epoch: active . epoch,
    candidate: candidate . summary . clone (),
    config_identity: config_identity (config),
    config_file_blake3: config_file_blake3 (config),
    source_catalog_blake3: source_catalog_blake3 (config),
    g0_graph_generation: selected . graph_generation,
    g0_manifest_revision: selected . manifest_revision,
    recovery: recovery_record (0, &[]),
    added_primary_ids: candidate . added_primary_ids . clone (),
    deleted_primary_ids: candidate . deleted_primary_ids . clone (),
    modified_primary_ids: candidate . modified_primary_ids . clone (),
    warnings: candidate . warnings . clone (),
    artifacts: Vec::new (),
  };
  Ok ((header, recovery, artifacts))
}

/// Reconstruct both complete semantic generations from the durable baseline
/// and its reversible delta.  Every `before` value must agree with G0; this
/// turns the delta into checked evidence rather than an unchecked edit list.
pub fn reconstruct_evidence (
  recovery : &MaintenanceRecoveryPayload,
) -> Result<ReconstructedEvidence, String> {
  if recovery . format_version != EVIDENCE_FORMAT_VERSION {
    return Err (format! ("unsupported recovery evidence version {}",
      recovery . format_version)); }
  let mut g0_nodes = BTreeMap::new ();
  for node in &recovery . g0_nodes {
    if node . pid . is_empty () {
      return Err ("recovery baseline contains an empty primary ID" . into ()); }
    if g0_nodes . insert (node . pid . clone (), node . clone ()) . is_some () {
      return Err (format! ("duplicate G0 recovery node {}", node . pid)); }
  }
  let mut g1_nodes = g0_nodes . clone ();
  let mut changed_nodes = BTreeSet::new ();
  for delta in &recovery . node_delta {
    if !changed_nodes . insert (delta . primary_id . clone ()) {
      return Err (format! ("duplicate recovery node delta {}",
        delta . primary_id)); }
    for value in [&delta . before, &delta . after] . into_iter () . flatten () {
      if value . pid != delta . primary_id {
        return Err (format! (
          "recovery node delta {} contains node {}",
          delta . primary_id, value . pid)); }
    }
    if g0_nodes . get (&delta . primary_id) != delta . before . as_ref () {
      return Err (format! ("recovery node delta {} does not match G0",
        delta . primary_id)); }
    match &delta . after {
      Some (node) => { g1_nodes . insert (delta . primary_id . clone (), node . clone ()); },
      None => { g1_nodes . remove (&delta . primary_id); },
    }
  }

  let g0_manifest = recovery . g0_manifest . clone ();
  let mut g1_manifest = g0_manifest . clone ();
  let mut changed_paths = BTreeSet::new ();
  for delta in &recovery . path_delta {
    if !changed_paths . insert (delta . path . clone ()) {
      return Err (format! ("duplicate recovery path delta {}",
        delta . path . display ())); }
    if g0_manifest . get (&delta . path) . copied () != delta . before {
      return Err (format! ("recovery path delta does not match G0 at {}",
        delta . path . display ())); }
    match delta . after {
      Some (digest) => { g1_manifest . insert (delta . path . clone (), digest); },
      None => { g1_manifest . remove (&delta . path); },
    }
  }
  Ok (ReconstructedEvidence {
    g0_manifest,
    g1_manifest,
    g0_nodes,
    g1_nodes,
  })
}

fn recovery_record (
  uncompressed_bytes : usize,
  bytes              : &[u8],
) -> RecoveryPayloadRecord {
  RecoveryPayloadRecord {
    relative_path: PathBuf::from (RECOVERY_FILENAME),
    encoding: RECOVERY_ENCODING . into (),
    compression: RECOVERY_COMPRESSION . into (),
    uncompressed_bytes: uncompressed_bytes as u64,
    byte_length: bytes . len () as u64,
    sha256: sha256_hex (bytes),
    blake3: blake3_hex (bytes),
  }
}

fn encode_recovery_payload (
  recovery : &MaintenanceRecoveryPayload,
) -> Result<Vec<u8>, String> {
  let mut bytes = Vec::new ();
  ciborium::ser::into_writer (recovery, &mut bytes)
    . map_err (|error| format! ("could not encode recovery evidence: {}", error))?;
  Ok (bytes)
}

fn decode_recovery_payload (
  bytes : &[u8],
) -> Result<MaintenanceRecoveryPayload, String> {
  let mut cursor = Cursor::new (bytes);
  let recovery = ciborium::de::from_reader (&mut cursor)
    . map_err (|error| format! ("invalid recovery evidence: {}", error))?;
  if cursor . position () != bytes . len () as u64 {
    return Err ("recovery evidence has trailing bytes" . into ()); }
  Ok (recovery)
}

fn artifact (
  relative_path : PathBuf,
  purpose       : &str,
  source_path   : Option<PathBuf>,
  bytes         : Vec<u8>,
) -> ArtifactBytes {
  ArtifactBytes {
    metadata: EvidenceArtifact {
      relative_path,
      purpose: purpose . into (),
      source_path,
      byte_length: bytes . len () as u64,
      sha256: sha256_hex (&bytes),
      blake3: blake3_hex (&bytes),
    },
    bytes,
  }
}

fn change_category (
  candidate : &ObservedDiskCandidate,
  pid       : &ID,
) -> Result<(&'static str, &'static str), String> {
  if candidate . added_primary_ids . contains (pid) {
    Ok (("new-nodes", "Added"))
  } else if candidate . deleted_primary_ids . contains (pid) {
    Ok (("deleted-nodes", "Deleted"))
  } else if candidate . modified_primary_ids . contains (pid) {
    Ok (("modified-nodes", "Modified"))
  } else {
    Err (format! ("changed node {} has no classification", pid))
  }
}

fn path_primary_id (path : &Path) -> Option<String> {
  path . file_stem () . and_then (|stem| stem . to_str ())
    . map (str::to_string)
}

fn source_record_sexp (
  index         : usize,
  path          : &Path,
  before_blake3 : Option<String>,
  after_blake3  : Option<String>,
  raw_after     : Option<&str>,
) -> Sexp {
  Sexp::List (vec![
    evidence_field ("path-key", &format! ("path-{:08}", index)),
    evidence_field ("display-path", &path . to_string_lossy ()),
    evidence_field ("before-blake3",
      before_blake3 . as_deref () . unwrap_or ("absent")),
    evidence_field ("after-blake3",
      after_blake3 . as_deref () . unwrap_or ("absent")),
    evidence_field ("raw-before-artifact", "unavailable"),
    evidence_field ("raw-after-artifact", raw_after . unwrap_or ("absent")),
  ])
}

fn evidence_field (key : &str, value : &str) -> Sexp {
  Sexp::List (vec![
    Sexp::Atom (Atom::S (key . into ())),
    Sexp::Atom (Atom::S (value . into ())),
  ])
}

fn verify_new_publication (
  directory      : &Path,
  header         : &MaintenanceEvidenceHeader,
  header_bytes   : &[u8],
  recovery_bytes : &[u8],
  artifacts      : &[ArtifactBytes],
) -> Result<PublishedMaintenanceEvidence, String> {
  require_private_directory (directory)?;
  validate_header (header, None, &header . config_identity)?;
  verify_exact_file (&directory . join (HEADER_FILENAME), header_bytes)?;
  verify_exact_file (
    &directory . join (RECOVERY_FILENAME), recovery_bytes)?;
  let expected_files = evidence_file_inventory (header)?;
  if header . artifacts != artifacts . iter ()
    . map (|artifact| artifact . metadata . clone ())
    . collect::<Vec<_>> ()
  {
    return Err ("evidence header has the wrong artifact inventory" . into ()); }
  let mut total_file_bytes = header_bytes . len () as u64
    + recovery_bytes . len () as u64;
  for artifact in artifacts {
    verify_exact_file (
      &directory . join (&artifact . metadata . relative_path),
      &artifact . bytes)?;
    total_file_bytes += artifact . bytes . len () as u64;
  }
  let actual_files = regular_file_inventory (directory)?;
  if actual_files != expected_files {
    return Err (format! (
      "evidence file inventory mismatch: expected {:?}, found {:?}",
      expected_files, actual_files)); }
  Ok (PublishedMaintenanceEvidence {
    path: directory . to_path_buf (),
    bundle_sha256: sha256_hex (header_bytes),
    artifact_count: artifacts . len (),
    total_file_bytes,
  })
}

fn validate_cached_publication (
  cached : &CachedPublishedEvidence,
) -> Result<(), String> {
  require_private_directory (&cached . publication . path)?;
  let header_path = cached . publication . path . join (HEADER_FILENAME);
  require_private_regular_file (&header_path)?;
  let header_bytes = fs::read (&header_path) . map_err (|error| format! (
    "could not read {}: {}", header_path . display (), error))?;
  if sha256_hex (&header_bytes) != cached . publication . bundle_sha256 {
    return Err ("evidence header changed after publication" . into ()); }
  let recovery_path = cached . publication . path
    . join (&cached . header . recovery . relative_path);
  validate_recovery_file (&recovery_path, &cached . header . recovery)?;
  let expected_files = evidence_file_inventory (&cached . header)?;
  let actual_files = regular_file_inventory (&cached . publication . path)?;
  if actual_files != expected_files {
    return Err (format! (
      "evidence file inventory mismatch: expected {:?}, found {:?}",
      expected_files, actual_files)); }
  Ok (( ))
}

fn evidence_file_inventory (
  header : &MaintenanceEvidenceHeader,
) -> Result<BTreeSet<PathBuf>, String> {
  let mut expected_files = BTreeSet::from ([
    PathBuf::from (HEADER_FILENAME),
    PathBuf::from (RECOVERY_FILENAME),
  ]);
  for artifact in &header . artifacts {
    validate_relative_artifact_path (&artifact . relative_path)?;
    if !expected_files . insert (artifact . relative_path . clone ()) {
      return Err (format! ("duplicate evidence artifact {}",
        artifact . relative_path . display ())); }
  }
  Ok (expected_files)
}

fn verify_exact_file (path : &Path, expected : &[u8]) -> Result<(), String> {
  require_private_regular_file (path)?;
  let actual = fs::read (path) . map_err (|error| format! (
    "could not reread {}: {}", path . display (), error))?;
  if actual != expected {
    return Err (format! ("durable evidence reread differed at {}",
      path . display ())); }
  Ok (( ))
}

fn load_evidence_directory (
  directory       : &Path,
  config_identity : &Path,
  incident        : Option<&IncidentId>,
) -> Result<(MaintenanceEvidenceBundle, PublishedMaintenanceEvidence), String> {
  let (header, publication, recovery_bytes) = load_evidence_header (
    directory, config_identity, incident, true)?;
  for artifact in &header . artifacts {
    validate_artifact_bytes (directory, artifact)?;
  }
  let compressed = recovery_bytes . expect ("recovery bytes were requested");
  let recovery_uncompressed = decode_compressed_recovery (
    &header . recovery, &compressed)?;
  let recovery = decode_recovery_payload (&recovery_uncompressed)?;
  validate_recovery_against_header (&header, &recovery)?;
  Ok ((MaintenanceEvidenceBundle { header, recovery }, publication))
}

fn load_evidence_header (
  directory                : &Path,
  config_identity          : &Path,
  incident                 : Option<&IncidentId>,
  verify_recovery_checksum : bool,
) -> Result<(
  MaintenanceEvidenceHeader,
  PublishedMaintenanceEvidence,
  Option<Vec<u8>>,
), String> {
  require_private_directory (directory)?;
  let header_path = directory . join (HEADER_FILENAME);
  let header_bytes = fs::read (&header_path)
    . map_err (|error| format! ("could not read {}: {}",
      header_path . display (), error))?;
  require_private_regular_file (&header_path)?;
  let header : MaintenanceEvidenceHeader = serde_yaml::from_slice (&header_bytes)
    . map_err (|error| format! ("invalid evidence header: {}", error))?;
  validate_header (&header, incident, config_identity)?;

  let expected_files = evidence_file_inventory (&header)?;
  let mut total_file_bytes = header_bytes . len () as u64;
  for artifact in &header . artifacts {
    let path = directory . join (&artifact . relative_path);
    require_private_regular_file (&path)?;
    let length = fs::metadata (&path) . map_err (|error| error . to_string ())?
      . len ();
    if length != artifact . byte_length {
      return Err (format! ("evidence artifact length mismatch at {}",
        artifact . relative_path . display ())); }
    total_file_bytes += length;
  }
  let recovery_path = directory . join (&header . recovery . relative_path);
  require_private_regular_file (&recovery_path)?;
  let recovery_length = fs::metadata (&recovery_path)
    . map_err (|error| error . to_string ())? . len ();
  if recovery_length != header . recovery . byte_length {
    return Err ("recovery evidence length mismatch" . into ()); }
  let recovery_bytes = if verify_recovery_checksum {
    Some (validate_recovery_file (&recovery_path, &header . recovery)?)
  } else { None };
  total_file_bytes += recovery_length;
  let actual_files = regular_file_inventory (directory)?;
  if actual_files != expected_files {
    return Err (format! (
      "evidence file inventory mismatch: expected {:?}, found {:?}",
      expected_files, actual_files)); }
  let artifact_count = header . artifacts . len ();
  Ok ((header, PublishedMaintenanceEvidence {
    path: directory . to_path_buf (),
    bundle_sha256: sha256_hex (&header_bytes),
    artifact_count,
    total_file_bytes,
  }, recovery_bytes))
}

fn validate_recovery_file (
  path   : &Path,
  record : &RecoveryPayloadRecord,
) -> Result<Vec<u8>, String> {
  require_private_regular_file (path)?;
  let bytes = fs::read (path) . map_err (|error| format! (
    "could not read {}: {}", path . display (), error))?;
  if bytes . len () as u64 != record . byte_length {
    return Err ("recovery evidence length mismatch" . into ()); }
  if sha256_hex (&bytes) != record . sha256
  || blake3_hex (&bytes) != record . blake3
  {
    return Err ("recovery evidence checksum mismatch" . into ()); }
  Ok (bytes)
}

fn validate_header (
  header          : &MaintenanceEvidenceHeader,
  incident        : Option<&IncidentId>,
  config_identity : &Path,
) -> Result<(), String> {
  if header . format_version != EVIDENCE_FORMAT_VERSION {
    return Err (format! ("unsupported evidence header version {}",
      header . format_version)); }
  if let Some (expected) = incident {
    if &header . incident_id != expected {
      return Err ("evidence directory has the wrong incident ID" . into ()); }}
  if header . config_identity != config_identity {
    return Err ("evidence bundle belongs to a different config" . into ()); }
  if header . candidate . base_graph_generation != header . g0_graph_generation
  || header . candidate . base_manifest_revision != header . g0_manifest_revision
  {
    return Err ("evidence header names inconsistent G0 generations" . into ()); }
  if header . recovery . relative_path != Path::new (RECOVERY_FILENAME)
  || header . recovery . encoding != RECOVERY_ENCODING
  || header . recovery . compression != RECOVERY_COMPRESSION
  {
    return Err ("unsupported recovery evidence representation" . into ()); }
  let classifications = [
    &header . added_primary_ids,
    &header . deleted_primary_ids,
    &header . modified_primary_ids,
  ];
  for left in 0..classifications . len () {
    for right in left + 1..classifications . len () {
      if !classifications[left] . is_disjoint (classifications[right]) {
        return Err ("evidence change classifications overlap" . into ()); }
    }
  }
  Ok (( ))
}

fn validate_artifact_bytes (
  directory : &Path,
  artifact  : &EvidenceArtifact,
) -> Result<Vec<u8>, String> {
  let bytes = fs::read (directory . join (&artifact . relative_path))
    . map_err (|error| error . to_string ())?;
  if bytes . len () as u64 != artifact . byte_length
  || sha256_hex (&bytes) != artifact . sha256
  || blake3_hex (&bytes) != artifact . blake3
  {
    return Err (format! ("evidence artifact checksum mismatch at {}",
      artifact . relative_path . display ())); }
  Ok (bytes)
}

fn decode_compressed_recovery (
  record : &RecoveryPayloadRecord,
  bytes  : &[u8],
) -> Result<Vec<u8>, String> {
  let mut decoder = zstd::stream::read::Decoder::new (Cursor::new (bytes))
    . map_err (|error| format! ("invalid compressed recovery evidence: {}",
      error))?;
  let limit = record . uncompressed_bytes . checked_add (1)
    . ok_or_else (|| "recovery evidence length overflows u64" . to_string ())?;
  let mut decoded = Vec::new ();
  decoder . by_ref () . take (limit) . read_to_end (&mut decoded)
    . map_err (|error| format! ("could not decompress recovery evidence: {}",
      error))?;
  if decoded . len () as u64 != record . uncompressed_bytes {
    return Err ("recovery evidence uncompressed length mismatch" . into ()); }
  Ok (decoded)
}

fn validate_recovery_against_header (
  header   : &MaintenanceEvidenceHeader,
  recovery : &MaintenanceRecoveryPayload,
) -> Result<(), String> {
  reconstruct_evidence (recovery)?;
  let added : BTreeSet<String> = header . added_primary_ids . iter ()
    . map (ToString::to_string) . collect ();
  let deleted : BTreeSet<String> = header . deleted_primary_ids . iter ()
    . map (ToString::to_string) . collect ();
  let modified : BTreeSet<String> = header . modified_primary_ids . iter ()
    . map (ToString::to_string) . collect ();
  let mut actual_added = BTreeSet::new ();
  let mut actual_deleted = BTreeSet::new ();
  let mut actual_modified = BTreeSet::new ();
  for delta in &recovery . node_delta {
    match (&delta . before, &delta . after) {
      (None, Some (_)) => { actual_added . insert (delta . primary_id . clone ()); },
      (Some (_), None) => { actual_deleted . insert (delta . primary_id . clone ()); },
      (Some (before), Some (after)) if before != after => {
        actual_modified . insert (delta . primary_id . clone ()); },
      _ => return Err (format! ("recovery node delta {} is not a change",
        delta . primary_id)),
    }
  }
  if (added, deleted, modified)
    != (actual_added . clone (), actual_deleted . clone (), actual_modified . clone ())
  {
    return Err ("recovery delta differs from header classifications" . into ()); }
  let changed : BTreeSet<String> = actual_added . into_iter ()
    . chain (actual_deleted) . chain (actual_modified) . collect ();
  if changed != header . candidate . changed_primary_ids . iter ()
    . cloned () . collect ()
  {
    return Err ("recovery delta differs from candidate summary" . into ()); }
  Ok (( ))
}

fn regular_file_inventory (root : &Path) -> Result<BTreeSet<PathBuf>, String> {
  let mut files = BTreeSet::new ();
  for entry in walkdir::WalkDir::new (root) . follow_links (false) {
    let entry = entry . map_err (|error| error . to_string ())?;
    if entry . path () == root { continue; }
    let metadata = fs::symlink_metadata (entry . path ())
      . map_err (|error| error . to_string ())?;
    if metadata . file_type () . is_symlink () {
      return Err (format! ("symlink is forbidden in evidence: {}",
        entry . path () . display ())); }
    if metadata . is_dir () {
      require_private_directory (entry . path ())?;
    } else if metadata . is_file () {
      require_private_regular_file (entry . path ())?;
      files . insert (entry . path () . strip_prefix (root)
        . map_err (|error| error . to_string ())? . to_path_buf ());
    } else {
      return Err (format! ("special file is forbidden in evidence: {}",
        entry . path () . display ())); }
  }
  Ok (files)
}

fn validate_relative_artifact_path (path : &Path) -> Result<(), String> {
  if path . is_absolute () || path . components () . any (|component|
      !matches! (component, std::path::Component::Normal (_)))
  {
    return Err (format! ("unsafe evidence artifact path {}", path . display ())); }
  if path == Path::new (HEADER_FILENAME)
  || path == Path::new (RECOVERY_FILENAME)
  {
    return Err ("artifact may not replace evidence metadata" . into ()); }
  Ok (( ))
}

fn write_private_file (path : &Path, bytes : &[u8]) -> Result<(), String> {
  let mut options = OpenOptions::new ();
  options . write (true) . create_new (true);
  #[cfg(unix)]
  options . mode (0o600);
  let mut file = options . open (path) . map_err (|error| format! (
    "could not create {}: {}", path . display (), error))?;
  file . write_all (bytes) . map_err (|error| error . to_string ())?;
  file . sync_all () . map_err (|error| error . to_string ())?;
  drop (file);
  Ok (( ))
}

fn create_private_directory (path : &Path) -> Result<(), String> {
  let mut builder = fs::DirBuilder::new ();
  #[cfg(unix)]
  builder . mode (0o700);
  builder . create (path) . map_err (|error| format! (
    "could not create {}: {}", path . display (), error))
}

fn create_private_directory_all (path : &Path) -> Result<(), String> {
  if fs::symlink_metadata (path) . is_ok () {
    return require_private_directory (path); }
  let mut missing = Vec::new ();
  let mut cursor = path;
  while fs::symlink_metadata (cursor) . is_err () {
    missing . push (cursor . to_path_buf ());
    cursor = cursor . parent ()
      . ok_or_else (|| format! ("directory has no existing parent: {}",
        path . display ()))?;
  }
  for directory in missing . into_iter () . rev () {
    match create_private_directory (&directory) {
      Ok (( )) => {},
      Err (_) if fs::symlink_metadata (&directory) . is_ok () =>
        require_private_directory (&directory)?,
      Err (error) => return Err (error),
    }
  }
  Ok (( ))
}

fn require_private_directory (path : &Path) -> Result<(), String> {
  let metadata = fs::symlink_metadata (path) . map_err (|error| format! (
    "could not inspect {}: {}", path . display (), error))?;
  if metadata . file_type () . is_symlink () || !metadata . is_dir () {
    return Err (format! ("evidence path is not a real directory: {}",
      path . display ())); }
  #[cfg(unix)]
  if metadata . permissions () . mode () & 0o777 != 0o700 {
    return Err (format! ("evidence directory is not mode 0700: {}",
      path . display ())); }
  Ok (( ))
}

fn require_private_regular_file (path : &Path) -> Result<(), String> {
  let metadata = fs::symlink_metadata (path) . map_err (|error| format! (
    "could not inspect {}: {}", path . display (), error))?;
  if metadata . file_type () . is_symlink () || !metadata . is_file () {
    return Err (format! ("evidence artifact is not a regular file: {}",
      path . display ())); }
  #[cfg(unix)]
  {
    if metadata . permissions () . mode () & 0o777 != 0o600 {
      return Err (format! ("evidence artifact is not mode 0600: {}",
        path . display ())); }
    if metadata . nlink () != 1 {
      return Err (format! ("evidence artifact is hard-linked: {}",
        path . display ())); }
  }
  Ok (( ))
}

fn sync_tree_directories (root : &Path) -> Result<(), String> {
  let mut directories : Vec<PathBuf> = walkdir::WalkDir::new (root)
    . follow_links (false) . into_iter () . filter_map (Result::ok)
    .filter (|entry| entry . file_type () . is_dir ())
    .map (|entry| entry . into_path ()) . collect ();
  directories . sort_by_key (|path| std::cmp::Reverse (path . components () . count ()));
  for directory in directories { sync_directory (&directory)?; }
  Ok (( ))
}

fn sync_directory (path : &Path) -> Result<(), String> {
  #[cfg(unix)]
  {
    let mut directory = File::open (path) . map_err (|error| error . to_string ())?;
    let mut byte = [0u8; 0];
    directory . read (&mut byte) . ok ();
    directory . sync_all () . map_err (|error| error . to_string ())?;
  }
  Ok (( ))
}

fn sha256_hex (bytes : &[u8]) -> String {
  format! ("{:x}", Sha256::digest (bytes))
}

fn blake3_hex (bytes : &[u8]) -> String {
  blake3::hash (bytes) . to_hex () . to_string ()
}

#[cfg(test)]
mod tests {
  use super::*;
  use crate::dbs::in_rust_graph::InRustGraph;
  use crate::dbs::filesystem::multiple_nodes::read_all_skg_files_with_manifest;
  use crate::dbs::filesystem::not_nodes::load_config;
  use crate::maintenance::{
    CandidateId,
    MaintenanceCoordinator,
    MaintenanceOrigin,
    ObservationSequence,
  };
  use crate::maintenance::candidate::SemanticChangeEvidence;
  use crate::types::misc::SkgConfig;
  use crate::types::nodes::complete::empty_node_complete;
  use crate::types::store_state::{PathDigest, SelectedStoreState};
  use std::sync::Arc;
  use std::time::{Duration, Instant};
  use tempfile::tempdir;

  #[test]
  fn rejects_undeclared_and_nonprivate_artifacts () {
    let temporary = tempdir () . unwrap ();
    let root = temporary . path () . join ("evidence");
    let store = MaintenanceEvidenceStore::at_root (
      root . clone (), PathBuf::from ("/config"));
    create_private_directory_all (&root) . unwrap ();
    let incident = IncidentId::new ();
    let directory = root . join (incident . as_str ());
    create_private_directory (&directory) . unwrap ();
    write_private_file (&directory . join ("undeclared"), b"x") . unwrap ();
    assert! (store . load (&incident) . is_err ());
  }

  #[test]
  fn relative_artifact_paths_cannot_escape () {
    assert! (validate_relative_artifact_path (Path::new ("bytes/1.bin")) . is_ok ());
    assert! (validate_relative_artifact_path (Path::new ("../outside")) . is_err ());
    assert! (validate_relative_artifact_path (Path::new ("/outside")) . is_err ());
  }

  #[test]
  fn recovery_payload_round_trips_complete_g0_and_g1 () {
    let modified = ID::from ("modified");
    let deleted = ID::from ("deleted");
    let added = ID::from ("added");
    let modified_before = semantic_node (&modified, "before");
    let modified_after = semantic_node (&modified, "after");
    let deleted_before = semantic_node (&deleted, "deleted");
    let added_after = semantic_node (&added, "added");
    let changed_path = PathBuf::from ("changed.skg");
    let deleted_path = PathBuf::from ("deleted.skg");
    let added_path = PathBuf::from ("added.skg");
    let before_changed_digest = PathDigest::of_bytes (b"before");
    let after_changed_digest = PathDigest::of_bytes (b"after");
    let deleted_digest = PathDigest::of_bytes (b"deleted");
    let added_digest = PathDigest::of_bytes (b"added");
    let recovery = MaintenanceRecoveryPayload {
      format_version: EVIDENCE_FORMAT_VERSION,
      g0_manifest: BTreeMap::from ([
        (changed_path . clone (), before_changed_digest),
        (deleted_path . clone (), deleted_digest),
      ]),
      g0_nodes: vec![modified_before . clone (), deleted_before . clone ()],
      node_delta: vec![
        ReversibleNodeDelta {
          primary_id: modified . to_string (),
          before: Some (modified_before . clone ()),
          after: Some (modified_after . clone ()),
        },
        ReversibleNodeDelta {
          primary_id: deleted . to_string (),
          before: Some (deleted_before . clone ()),
          after: None,
        },
        ReversibleNodeDelta {
          primary_id: added . to_string (),
          before: None,
          after: Some (added_after . clone ()),
        },
      ],
      path_delta: vec![
        ReversiblePathDelta {
          path: changed_path . clone (),
          before: Some (before_changed_digest),
          after: Some (after_changed_digest),
        },
        ReversiblePathDelta {
          path: deleted_path . clone (),
          before: Some (deleted_digest),
          after: None,
        },
        ReversiblePathDelta {
          path: added_path . clone (),
          before: None,
          after: Some (added_digest),
        },
      ],
    };
    let encoded = encode_recovery_payload (&recovery) . unwrap ();
    let decoded = decode_recovery_payload (&encoded) . unwrap ();
    assert_eq! (decoded, recovery);
    let reconstructed = reconstruct_evidence (&decoded) . unwrap ();
    assert_eq! (reconstructed . g0_nodes, BTreeMap::from ([
      (modified . to_string (), modified_before),
      (deleted . to_string (), deleted_before),
    ]));
    assert_eq! (reconstructed . g1_nodes, BTreeMap::from ([
      (modified . to_string (), modified_after),
      (added . to_string (), added_after),
    ]));
    assert_eq! (reconstructed . g0_manifest, BTreeMap::from ([
      (changed_path . clone (), before_changed_digest),
      (deleted_path, deleted_digest),
    ]));
    assert_eq! (reconstructed . g1_manifest, BTreeMap::from ([
      (changed_path, after_changed_digest),
      (added_path, added_digest),
    ]));
  }

  #[test]
  fn recovery_payload_rejects_a_delta_whose_before_value_is_false () {
    let pid = ID::from ("node");
    let recovery = MaintenanceRecoveryPayload {
      format_version: EVIDENCE_FORMAT_VERSION,
      g0_manifest: Default::default (),
      g0_nodes: vec![semantic_node (&pid, "actual")],
      node_delta: vec![ReversibleNodeDelta {
        primary_id: pid . to_string (),
        before: Some (semantic_node (&pid, "false")),
        after: Some (semantic_node (&pid, "after")),
      }],
      path_delta: Vec::new (),
    };
    assert! (reconstruct_evidence (&recovery) . unwrap_err ()
      . contains ("does not match G0"));
  }

  #[test]
  fn one_node_delta_does_not_serialize_a_second_corpus () {
    #[derive(Serialize)]
    struct TwoFullGenerations<'a> {
      g0_nodes : &'a [SemanticNodeEvidence],
      g1_nodes : &'a [SemanticNodeEvidence],
    }

    let mut g0_nodes = Vec::new ();
    for index in 0..512 {
      let pid = ID::from (format! ("node-{:04}", index));
      let mut node = semantic_node (&pid, &format! ("title-{:04}", index));
      node . body = Some (format! ("unique-body-{:04}-{}",
        index, "x" . repeat (256)));
      g0_nodes . push (node);
    }
    let before = g0_nodes[0] . clone ();
    let mut after = before . clone ();
    after . title = "changed title" . into ();
    let recovery = MaintenanceRecoveryPayload {
      format_version: EVIDENCE_FORMAT_VERSION,
      g0_manifest: Default::default (),
      g0_nodes: g0_nodes . clone (),
      node_delta: vec![ReversibleNodeDelta {
        primary_id: before . pid . clone (),
        before: Some (before),
        after: Some (after),
      }],
      path_delta: Vec::new (),
    };
    let compact_bytes = encode_recovery_payload (&recovery) . unwrap ();
    let mut duplicated_bytes = Vec::new ();
    ciborium::ser::into_writer (&TwoFullGenerations {
      g0_nodes: &g0_nodes,
      g1_nodes: &g0_nodes,
    }, &mut duplicated_bytes) . unwrap ();
    assert! (compact_bytes . len () * 10 < duplicated_bytes . len () * 6,
      "one-baseline payload was {} bytes; duplicated corpus was {} bytes",
      compact_bytes . len (), duplicated_bytes . len ());
  }

  /// Manual regression benchmark for the repository's approximately 30,000-
  /// node development corpus.  It writes only to a temporary evidence root.
  #[test]
  #[ignore = "requires the repository's real data/skgconfig.toml corpus"]
  fn real_corpus_one_node_publication_stays_under_three_seconds () {
    let config = load_config ("data/skgconfig.toml") . unwrap ();
    let loaded = read_all_skg_files_with_manifest (&config) . unwrap ();
    let selected = SelectedStoreState::initial (
      InRustGraph::from_nodecompletes (&loaded . nodes),
      loaded . manifest);
    let before_complete = nodecompletes_from_graph (&selected . graph)
      . into_iter () . next () . expect ("real corpus is nonempty");
    let mut after_complete = before_complete . clone ();
    after_complete . title . push_str (" [evidence latency probe]");
    let pid = before_complete . pid . clone ();
    let before = SemanticNodeEvidence::from (&before_complete);
    let after = SemanticNodeEvidence::from (&after_complete);
    let mut after_nodes = nodecompletes_from_graph (&selected . graph);
    let changed = after_nodes . iter_mut ()
      . find (|node| node . pid == pid) . unwrap ();
    *changed = after_complete;
    let summary = CandidateSummary {
      id: CandidateId::new (),
      base_graph_generation: selected . graph_generation,
      base_manifest_revision: selected . manifest_revision,
      covered_sequence: ObservationSequence::INITIAL,
      changed_primary_ids: vec![pid . to_string ()],
    };
    let candidate = ObservedDiskCandidate {
      summary: summary . clone (),
      config_identity: config_identity (&config),
      config_file_blake3: config_file_blake3 (&config),
      source_catalog_blake3: source_catalog_blake3 (&config),
      config: Arc::new (config . clone ()),
      manifest: (*selected . manifest) . clone (),
      base_graph: selected . graph . clone (),
      graph: Arc::new (InRustGraph::from_nodecompletes (&after_nodes)),
      definitions: Vec::new (),
      added_primary_ids: Default::default (),
      deleted_primary_ids: Default::default (),
      modified_primary_ids: BTreeSet::from ([pid . clone ()]),
      evidence: BTreeMap::from ([
        (pid, SemanticChangeEvidence {
          before: Some (before),
          after: Some (after),
          diff: "latency probe" . into (),
        }),
      ]),
      selected_bytes: Default::default (),
      warnings: Vec::new (),
      load_violations: Vec::new (),
      disk_fence: crate::maintenance::candidate::CandidateDiskFence::Targeted (
        Default::default ()),
    };
    let mut coordinator = MaintenanceCoordinator::new ();
    let active = coordinator . begin (
      MaintenanceOrigin::PendingReconciliation, Some (summary)) . unwrap ();
    let temporary = tempdir () . unwrap ();
    let store = MaintenanceEvidenceStore::at_root (
      temporary . path () . join ("evidence"), config_identity (&config));
    let started = Instant::now ();
    let publication = store . publish_candidate (
      &active, &config, &selected, &candidate) . unwrap ();
    let publish_elapsed = started . elapsed ();
    let load_started = Instant::now ();
    store . load (&active . incident_id) . unwrap ();
    let load_elapsed = load_started . elapsed ();
    let transfer_started = Instant::now ();
    store . client_bundle (&active . incident_id) . unwrap ();
    let transfer_elapsed = transfer_started . elapsed ();
    eprintln! (
      "version-3 real-corpus evidence: publish {:?}, recovery load {:?}, client transfer {:?}, {} bytes",
      publish_elapsed, load_elapsed, transfer_elapsed,
      publication . total_file_bytes);
    assert! (publish_elapsed < Duration::from_secs (3),
      "one-node evidence publication took {:?}", publish_elapsed);
    assert! (load_elapsed < Duration::from_secs (3),
      "one-node recovery evidence load took {:?}", load_elapsed);
    assert! (transfer_elapsed < Duration::from_secs (1),
      "one-node client evidence transfer took {:?}", transfer_elapsed);
    assert! (publication . total_file_bytes < 10 * 1024 * 1024,
      "one-node evidence publication retained {} bytes",
      publication . total_file_bytes);
  }

  #[test]
  fn candidate_bundle_round_trips_and_rejects_an_extra_file () {
    let temporary = tempdir () . unwrap ();
    let config_path = temporary . path () . join ("skgconfig.toml");
    fs::write (&config_path, b"") . unwrap ();
    let mut config = SkgConfig::dummyFromSources (Default::default ());
    config . config_path = config_path . clone ();
    let selected = SelectedStoreState::initial (
      InRustGraph::new (), Default::default ());
    let summary = CandidateSummary {
      id: CandidateId::new (),
      base_graph_generation: selected . graph_generation,
      base_manifest_revision: selected . manifest_revision,
      covered_sequence: ObservationSequence::INITIAL,
      changed_primary_ids: Vec::new (),
    };
    let candidate = ObservedDiskCandidate {
      summary: summary . clone (),
      config_identity: config_identity (&config),
      config_file_blake3:
        crate::maintenance::candidate::config_file_blake3 (&config),
      source_catalog_blake3: source_catalog_blake3 (&config),
      config: Arc::new (config . clone ()),
      manifest: Default::default (),
      base_graph: Arc::new (InRustGraph::new ()),
      graph: Arc::new (InRustGraph::new ()),
      definitions: Vec::new (),
      added_primary_ids: Default::default (),
      deleted_primary_ids: Default::default (),
      modified_primary_ids: Default::default (),
      evidence: Default::default (),
      selected_bytes: Default::default (),
      warnings: Vec::new (),
      load_violations: Vec::new (),
      disk_fence: crate::maintenance::candidate::CandidateDiskFence::Complete,
    };
    let mut coordinator = MaintenanceCoordinator::new ();
    let active = coordinator . begin (
      MaintenanceOrigin::PendingReconciliation, Some (summary)) . unwrap ();
    let store = MaintenanceEvidenceStore::at_root (
      temporary . path () . join ("evidence"), config_identity (&config));
    let publication = store . publish_candidate (
      &active, &config, &selected, &candidate) . unwrap ();
    let (loaded, loaded_publication) = store . load (&active . incident_id) . unwrap ();
    assert_eq! (loaded . header . candidate, candidate . summary);
    assert_eq! (loaded_publication, publication);
    let client = store . client_bundle (&active . incident_id) . unwrap ();
    assert! (client . artifacts . is_empty ());
    assert! (client . bytes . is_empty ());
    assert_eq! (client . artifact_bytes_sha256, sha256_hex (&[]));
    let mut replacement_candidate = candidate . clone ();
    replacement_candidate . summary . id = CandidateId::new ();
    let mut replacement_active = active . clone ();
    replacement_active . candidate = Some (
      replacement_candidate . summary . clone ());
    let replacement_publication = store . publish_candidate (
      &replacement_active, &config, &selected, &replacement_candidate)
      . unwrap ();
    assert_eq! (store . load (&active . incident_id) . unwrap () . 0
      . header . candidate, replacement_candidate . summary);
    let preserved_prefix = format! (
      "{}--superseded--{}--", active . incident_id, candidate . summary . id);
    assert! (fs::read_dir (&store . directory) . unwrap ()
      . filter_map (Result::ok) . any (|entry| entry . file_name ()
        . to_string_lossy () . starts_with (&preserved_prefix)));
    write_private_file (
      &replacement_publication . path . join ("extra"), b"no") . unwrap ();
    assert! (store . load (&active . incident_id) . is_err ());
  }

  #[test]
  fn client_bundle_uses_safe_final_paths_and_exact_ordered_slices () {
    let temporary = tempdir () . unwrap ();
    let config_path = temporary . path () . join ("skgconfig.toml");
    fs::write (&config_path, b"") . unwrap ();
    let mut config = SkgConfig::dummyFromSources (Default::default ());
    config . config_path = config_path;
    let pid = ID::from ("node one");
    let path = temporary . path () . join ("node one.skg");
    let before_bytes = b"before telescope\n";
    let after_bytes = vec![0xff, 0xfe, b'\n'];
    let mut before_complete = empty_node_complete ();
    before_complete . pid = pid . clone ();
    before_complete . title = "before" . into ();
    before_complete . source = "source" . into ();
    let mut after_complete = before_complete . clone ();
    after_complete . title = "after" . into ();
    let selected = SelectedStoreState::initial (
      InRustGraph::from_nodecompletes (&[before_complete . clone ()]),
      BTreeMap::from ([
        (path . clone (), PathDigest::of_bytes (before_bytes)),
      ]));
    let summary = CandidateSummary {
      id: CandidateId::new (),
      base_graph_generation: selected . graph_generation,
      base_manifest_revision: selected . manifest_revision,
      covered_sequence: ObservationSequence::INITIAL,
      changed_primary_ids: vec![pid . to_string ()],
    };
    let before = semantic_node (&pid, "before");
    let after = semantic_node (&pid, "after");
    let candidate = ObservedDiskCandidate {
      summary: summary . clone (),
      config_identity: config_identity (&config),
      config_file_blake3:
        crate::maintenance::candidate::config_file_blake3 (&config),
      source_catalog_blake3: source_catalog_blake3 (&config),
      config: Arc::new (config . clone ()),
      manifest: BTreeMap::from ([
        (path . clone (), PathDigest::of_bytes (&after_bytes)),
      ]),
      base_graph: Arc::new (
        InRustGraph::from_nodecompletes (&[before_complete])),
      graph: Arc::new (InRustGraph::from_nodecompletes (&[after_complete])),
      definitions: Vec::new (),
      added_primary_ids: Default::default (),
      deleted_primary_ids: Default::default (),
      modified_primary_ids: BTreeSet::from ([pid . clone ()]),
      evidence: BTreeMap::from ([
        (pid . clone (), SemanticChangeEvidence {
          before: Some (before . clone ()), after: Some (after . clone ()),
          diff: "-before\n+after\n" . into (),
        }),
      ]),
      selected_bytes: BTreeMap::from ([(path, after_bytes . clone ())]),
      warnings: Vec::new (),
      load_violations: Vec::new (),
      disk_fence: crate::maintenance::candidate::CandidateDiskFence::Complete,
    };
    let mut coordinator = MaintenanceCoordinator::new ();
    let active = coordinator . begin (
      MaintenanceOrigin::PendingReconciliation, Some (summary)) . unwrap ();
    let store = MaintenanceEvidenceStore::at_root (
      temporary . path () . join ("evidence"), config_identity (&config));
    let publication = store . publish_candidate (
      &active, &config, &selected, &candidate) . unwrap ();
    let (loaded, _) = store . load (&active . incident_id) . unwrap ();
    assert_eq! (loaded . recovery . g0_nodes . len (), 1);
    assert_eq! (loaded . recovery . node_delta . len (), 1);
    let reconstructed = reconstruct_evidence (&loaded . recovery) . unwrap ();
    assert_eq! (reconstructed . g0_nodes . get (&pid . to_string ()),
      Some (&before));
    assert_eq! (reconstructed . g1_nodes . get (&pid . to_string ()),
      Some (&after));
    assert_eq! (reconstructed . g0_manifest, *selected . manifest);
    assert_eq! (reconstructed . g1_manifest, candidate . manifest);
    assert! (!publication . path . join ("bundle.yaml") . exists ());
    assert! (publication . path . join (HEADER_FILENAME) . exists ());
    assert! (publication . path . join (RECOVERY_FILENAME) . exists ());
    let client = store . client_bundle (&active . incident_id) . unwrap ();
    assert_eq! (store . client_bundle (&active . incident_id) . unwrap (), client);

    assert_eq! (client . artifacts . len (), publication . artifact_count);
    assert! (client . artifacts . iter () . all (|record|
      record . relative_path . starts_with (
        "modified-nodes/node-00000000-")
      && !record . relative_path . contains ("..")));
    let mut expected_offset = 0;
    for record in &client . artifacts {
      assert_eq! (record . byte_offset, expected_offset);
      let start = record . byte_offset as usize;
      let end = start + record . byte_length as usize;
      assert_eq! (sha256_hex (&client . bytes[start..end]), record . sha256);
      expected_offset += record . byte_length;
    }
    let raw = client . artifacts . iter ()
      . find (|record| record . purpose == "raw-after") . unwrap ();
    let start = raw . byte_offset as usize;
    let end = start + raw . byte_length as usize;
    assert_eq! (&client . bytes[start..end], after_bytes);

    let recovery_path = publication . path . join (RECOVERY_FILENAME);
    let mut corrupt = fs::read (&recovery_path) . unwrap ();
    corrupt[0] ^= 0xff;
    fs::write (&recovery_path, corrupt) . unwrap ();
    assert! (store . load (&active . incident_id) . unwrap_err ()
      . contains ("recovery evidence checksum mismatch"));
    assert! (store . client_bundle (&active . incident_id) . unwrap_err ()
      . contains ("recovery evidence checksum mismatch"));
  }

  fn semantic_node (pid : &ID, title : &str) -> SemanticNodeEvidence {
    SemanticNodeEvidence {
      format_version: 1,
      pid: pid . to_string (),
      source: "source" . into (),
      title: title . into (),
      ugly_telescope: false,
      extra_ids: Vec::new (),
      body: None,
      aliases: None,
      contains: Vec::new (),
      subscribes_to: None,
      hides_from_its_subscriptions: None,
      overrides_view_of: None,
      file_properties: Vec::new (),
    }
  }
}
