;;; -*- lexical-binding: t; -*-
;;;
;;; PURPOSE:
;;; Transform s-expressions using
;;; an abstract, declarative set of pattern-matching rules.
;;; Currently, it is used to turn a text-only metadata sexp
;;; into a shorter, colorful visual representation.
;;; But it might turn out to be useful for other things.

(require 'cl-lib)
(require 'skg-shared)

(defun skg-transform-sexp-flat
  (object rules)
  "Applies 'rules' to 'object' to generate an output expression.
Has no side effects.
The test suite demonstrates how rules are interpreted,
perhaps better than the following explanation.
.
Both 'object' and 'rules' can be nested s-exps.
The first element of each s-expr at any level should be an atom,
which we'll usually call the 'label'.
(I say 'usually' because there's an exception:
if the expression includes a style directive,
as described below, then that precedes the label.
Both the style directive and the label are atoms.)
The rest of the list can be anything.
The leaf-lists (lists with no sublists) of a rule
contain, after the label, a series of symbols,
 which will be concatenated in the result with ':' between them.
.
Consider such a leaf-list in a rule, with two elts, 'a' and 'b'.
The rules indicates how to transform 'a' into 'b'.
('a' is a label in the rule but is an atom in the object.)
If the transformation applies, it is appended to the output expression.
The transformation only applies if the atom 'a' from 'rules'
can be found in 'object', and both are nested such that
the sequence of 'label's leading to each is the same.
  So for instance if object=(a (b c)) and rules=(a (b (c d))),
  the output would be 'd', but if rules had been (b (a (c d)))
  the output would instead be the empty list.
  (In the first case if the rule were instead '(a (b (c d e)))',
  the output would be 'd:e'.)
.
There are several keywords that receive special treatment:
the style names (the styles of 'shared/herald-styles.json' in
capitals, such as STOP, GO, NORMAL, MEDIUM, and HIGH); the sexp-
shape markers ANY and IT; the positional marker ABUT; and the
directive INTERC. Each is described below.
.
ANY indicates that the path of labels exists.
Regardless of what the leaf sexp in the object at that path contains,
the elements listed after ANY in the corresponding leaf-sexp
of the rule will be appended to the output. This is true
even if the object leaf-sexp is a singleton,
containing only the label.
  So for instance, if our rule is (a (b (ANY x))),
  the output would be (x) for any of the following objects:
    (a (b))
    (a (b c))
    (a c (b c))
  whereas for these objects, the output would be ():
    (b a)
    (a b)
    (a)
.
In an ANY leaf-sexp in a rule,
IT refers to any value found after the label
of the corresponding leaf-sexp in 'object'.
Outside of an ANY leaf-sexp in a rule, IT is meaningless.
  So for instance:
    object = (a (b c))
    rule = (a (b (ANY x IT y)))
    output = (x:c:y)
  Note that a single IT can match multiple values:
    object = (a (b c d))
    rule = (a (b (ANY x IT y)))
    output = (x:c:y x:d:y)
.
The style names are style keywords that
can appear as the first element of any rule list, before the
label. They set the style for all output generated by that rule
and any nested rules, unless overridden by a deeper style keyword.
The style is applied as an `skg-style' text property on the
output string; a renderer maps that to a face at display time.
  For example, if
    rule = (a (STOP b (c d) (GO e f))),
    then any 'd' produced by the rule will have style STOP,
    but any 'f' produced by the rule will have style GO.
.
ABUT is a marker that may appear immediately after a leaf rule's
label (and optional style). A token emitted by an ABUT rule
carries an `skg-abut' property on its first character. Renderers
treat that as a signal to join the token to its predecessor with
no separator. Typical use: gluing a modifier character onto the
token it decorates (e.g. a peace symbol onto a affectsParent character).
.
INTERC is a directive for rules of the form
    ([STYLE] INTERC SEP [LABEL] [PREFIX...] SUB-RULES...)
with SLOT semantics: each list sub-rule contributes exactly one
slot whose content is the concatenation of that sub-rule's
outputs (or the empty string if the sub-rule doesn't fire).
Nonempty slots are joined with SEP, the literal string PREFIX is
prepended, and the result is emitted as a single token. If every
slot is empty, no token is emitted.
  LABEL is optional: with it, INTERC matches children of OBJECT
  bearing that label; without it, it runs its sub-rules against
  OBJECT directly (useful when server-side atoms already sit at
  the current level).
  Per-sub-rule styles are preserved on the output string's
  character ranges; SEP and PREFIX take INTERC's own style.
.
A leaf-list in a rule can be vacuous, a singleton label.
This is just to demonstrate that the possibility has been considered,
and does not affect the output.
Such singleton leaf-lists can be omitted from the rule to no effect."
  (let ((header (and (listp rules) (skg--rule-header rules))))
    (if (or (not (listp object))
            (not header)
            (not (equal (car object) (alist-get 'label header))))
        '()
      (skg--transform-sexp-flat-from object header nil))))

(defun skg--propertize-style (s style)
  "Return a copy of S with `skg-style' set to STYLE over its full
range. Returns S unchanged when STYLE is nil or S is empty. The
engine uses `skg-style' as the neutral representation of
\"styles\" on tokens; a rendering layer (for heralds, that's
`heralds--tokens->text') converts it to a face at display time."
  (let ((copy (copy-sequence s)))
    (when (and style (> (length copy) 0))
      (put-text-property 0 (length copy) 'skg-style style copy))
    copy))

(defun skg--tokens->string
  (tokens
    current-style)
  "Join TOKENS with `:' and propertize the result with CURRENT-STYLE."
  (skg--propertize-style
   (mapconcat #'skg--token->string tokens ":")
   current-style))

(defun skg--token->string
  (token)
  "Convert TOKEN to string. Symbols and strings are common (rule
child labels); numbers reach here via ANY/IT matches on numeric
atoms in the input (e.g. counts like `(containers 3)'). Anything
else is `format'-ed as a last resort."
  (cond
    ((symbolp token) (symbol-name token))
    ((stringp token) token)
    (t (format "%s" token))))

(defun skg--style-keyword-p
  (sym)
  "Return t if SYM is a style keyword: a style name from
'shared/herald-styles.json', in capitals."
  (memq sym (skg-shared-style-keywords)))

(defun skg--rule-header (rule)
  "Parse RULE once and return an alist classifying it.
Keys:
  kind      -- one of `interc', `any-leaf', `atomic-leaf', `non-leaf'.
  style     -- the style keyword at the rule's head, or nil.
  label     -- the rule's label symbol (required for non-INTERC;
               optional for INTERC).
  separator -- INTERC's separator string, or nil for non-INTERC.
  abut      -- t if the rule carries an ABUT marker (leaf-only).
  children  -- the rule's post-header tail: literal strings are
               prefix material, list children are sub-rules to
               recurse into.

Grammar handled:
  RULE        ::= [STYLE] (INTERC-BODY | SIMPLE-BODY)
  INTERC-BODY ::= INTERC SEP [LABEL] CHILDREN...
  SIMPLE-BODY ::= LABEL [ABUT] CHILDREN...

Classification for simple bodies: `non-leaf' if any child is a
list; `any-leaf' if label is ANY (and it's a leaf);
`atomic-leaf' otherwise."
  (let ((tail rule)
        (style nil)
        (kind nil)
        (label nil)
        (separator nil)
        (abut nil)
        (children nil))
    (when (and (consp tail) (skg--style-keyword-p (car tail)))
      (setq style (car tail))
      (setq tail (cdr tail)))
    (cond
      ((eq (car-safe tail) 'INTERC)
       (setq kind 'interc)
       (setq tail (cdr tail))
       (setq separator (car tail))
       (setq tail (cdr tail))
       (when (and (consp tail)
                  (symbolp (car tail))
                  (car tail)
                  (not (skg--style-keyword-p (car tail))))
         (setq label (car tail))
         (setq tail (cdr tail)))
       (setq children tail))
      (t
       (setq label (car-safe tail))
       (setq tail (cdr tail))
       (when (eq (car-safe tail) 'ABUT)
         (setq abut t)
         (setq tail (cdr tail)))
       (setq children tail)
       (setq kind
             (cond
               ((cl-some #'listp children) 'non-leaf)
               ((eq label 'ANY)            'any-leaf)
               (t                          'atomic-leaf)))))
    (list (cons 'kind kind)
          (cons 'style style)
          (cons 'label label)
          (cons 'separator separator)
          (cons 'abut abut)
          (cons 'children children))))

(defun skg--transform-sexp-flat-from
  (object
    header
    current-style)
  "Transform OBJECT using HEADER (a parsed rule) with CURRENT-STYLE.
String-literal children of the header are collected into a prefix.
When any list child fires, the prefix is concatenated (no
separator) before each of its outputs. When no list child fires
but the prefix is non-empty, the prefix is emitted alone -- so
rules like (STOP deleted \"DELETED\" (id) (repo)) serve as a
label for the structure even when their sub-rules are vacuous."
  (let* ((new-style
           (or (alist-get 'style header) current-style))
         (children (alist-get 'children header))
         (prefix
           (mapconcat
             #'identity
             (cl-remove-if-not #'stringp children)
             ""))
         (results '()))
    (dolist (rc children)
      (when (listp rc)
        (setq results
              (nconc results
                     (skg--transform-sexp-flat-dispatch
                      object rc new-style)))))
    (cond
      ((string-empty-p prefix) results)
      ((null results)
       (list (skg--prepend-prefix "" prefix new-style)))
      (t
       (mapcar
         (lambda (r) (skg--prepend-prefix r prefix new-style))
         results)))))

(defun skg--prepend-prefix
  (output prefix style)
  "Return PREFIX concatenated with OUTPUT. PREFIX carries STYLE
via `skg-style'; OUTPUT's own text properties are preserved."
  (concat (skg--propertize-style prefix style) output))

(defun skg--transform-sexp-flat-dispatch
  (object
    rule-child
    current-style)
  "Dispatch RULE-CHILD application to OBJECT with CURRENT-STYLE.
Parses RULE-CHILD's header exactly once and pcases on kind."
  (if (not (listp rule-child))
      '()
    (let ((header (skg--rule-header rule-child)))
      (pcase (alist-get 'kind header)
        ('interc      (skg--apply-interc        object header current-style))
        ('any-leaf    (skg--apply-any-leaf      object header current-style))
        ('atomic-leaf (skg--apply-ordinary-leaf object header current-style))
        ('non-leaf    (skg--apply-non-leaf      object header current-style))))))

(defun skg--apply-interc
  (object header current-style)
  "Apply an INTERC HEADER to OBJECT with CURRENT-STYLE.

Two modes depending on whether the rule has a LABEL:

- With LABEL: for each child of OBJECT matching that label, run
  the sub-rules against it and emit one combined token.
- Without LABEL: run the sub-rules against OBJECT itself and emit
  at most one combined token. Used when the server already emits
  the raw atoms at the current level (e.g. `(containers N)' and
  `(contents M)' as siblings inside `(graphStats ...)') and no
  wrapper form is needed.

In both modes, each sub-rule contributes one slot; nonempty slots
are joined with the header's SEPARATOR; a literal-string prefix is
prepended; the token is suppressed if every slot is empty.

Colors: the separator and prefix take the rule's inherited style
context (its own style if set, otherwise CURRENT-STYLE). Each
slot preserves whatever styles its sub-rule's outputs carry, via
text properties on character ranges."
  (let* ((new-style (or (alist-get 'style header) current-style))
         (sep       (alist-get 'separator header))
         (label     (alist-get 'label header))
         (children  (alist-get 'children header))
         (prefix-str (mapconcat #'identity
                       (cl-remove-if-not #'stringp children) ""))
         (targets (if label
                      (skg--object-children-with-label object label)
                    (list object)))
         (results '()))
    (dolist (target targets)
      (let ((slots '()))
        (dolist (rc children)
          (when (listp rc)
            (let ((outs (skg--transform-sexp-flat-dispatch
                         target rc new-style)))
              (push (apply #'concat outs) slots))))
        (setq slots (nreverse slots))
        (when (cl-some (lambda (s) (> (length s) 0)) slots)
          (push (skg--interc--build-token
                 prefix-str sep slots new-style)
                results))))
    (nreverse results)))

(defun skg--interc--build-token (prefix sep slots style)
  "Build an INTERC token: PREFIX + JOIN(SLOTS, SEP), skipping empty
slots. PREFIX and SEP both carry STYLE via `skg-style'. Each slot
string's own text properties survive the concatenation, so
per-sub-rule styles remain visible as ranges on the final token."
  (let ((out (skg--propertize-style prefix style))
        (first t))
    (dolist (slot (cl-remove-if (lambda (slot) (= (length slot) 0)) slots))
      (unless first
        (setq out (concat out
                          (skg--propertize-style sep style))))
      (setq out (concat out slot))
      (setq first nil))
    out))

(defun skg--apply-non-leaf
  (object
    header
    current-style)
  "Apply non-leaf HEADER to OBJECT with CURRENT-STYLE."
  (let
      ((matches
          (skg--object-children-with-label
            object (alist-get 'label header)))
        (results '()))
    (dolist
        (match matches)
      (setq results
            (nconc results
                   (skg--transform-sexp-flat-from
                    match header current-style))))
    results))

(defun skg--apply-ordinary-leaf
  (object
    header
    current-style)
  "Apply ordinary leaf HEADER to OBJECT with CURRENT-STYLE."
  (let*
      ((style   (or (alist-get 'style header) current-style))
       (label   (alist-get 'label header))
       (abut    (alist-get 'abut header))
       (tokens  (alist-get 'children header))
       (matches (skg--object-atomic-matches object label))
       (results '()))
    (when tokens
      (dolist
          (_ matches)
        (let ((tok (skg--tokens->string tokens style)))
          (skg--maybe-mark-abut tok abut)
          (setq results (nconc results (list tok))))))
    results))

(defun skg--apply-any-leaf
  (object
    header
    current-style)
  "Apply ANY leaf HEADER to OBJECT with CURRENT-STYLE."
  (let*
      ((style       (or (alist-get 'style header) current-style))
       (abut        (alist-get 'abut header))
       (tokens      (alist-get 'children header))
       (tail-values (cdr object))
       (results '()))
    (cond
      ((null tokens) '())
      ((memq 'IT tokens)
        (dolist
            (tail-value tail-values)
          (let ((tok (skg--tokens->string
                      (skg--replace-it tokens tail-value) style)))
            (skg--maybe-mark-abut tok abut)
            (setq results (nconc results (list tok)))))
        results)
      (t
        (let ((tok (skg--tokens->string tokens style)))
          (skg--maybe-mark-abut tok abut)
          (list tok))))))

(defun skg--maybe-mark-abut (tok abut)
  "If ABUT is non-nil and TOK is a non-empty string, set the
`skg-abut' text property on its first character. Renderers read
that property to decide whether to emit a separator before TOK."
  (when (and abut (stringp tok) (> (length tok) 0))
    (put-text-property 0 1 'skg-abut t tok)))

(defun skg--replace-it
  (tokens
    tail-value)
  (mapcar
    (lambda
      (token)
      (if
          (eq token 'IT)
          tail-value
        token))
    tokens))

(defun skg--object-children-with-label
  (object
    label)
  (cl-loop
    for element in (cdr object)
    when
    (and
      (listp element)
      (equal (car element) label))
    collect element))

(defun skg--object-atomic-matches
  (object
    label)
  (cl-loop
    for element in (cdr object)
    when
    (and
      (not (listp element))
      (equal element label))
    collect element))

(provide 'skg-lens)
