;;; -*- lexical-binding: t; -*-
;;;
;;; PURPOSE:
;;; Transform s-expressions using
;;; an abstract, declarative set of pattern-matching rules.
;;; Currently, it is used to turn a text-only metadata sexp
;;; into a shorter, colorful visual representation.
;;; But it might turn out to be useful for other things.

(require 'cl-lib)

(defun skg-transform-sexp-flat
  (object rules)
  "Applies 'rules' to 'object' to generate an output expression.
Has no side effects.
The test suite demonstrates how rules are interpreted,
perhaps better than the following explanation.
.
Both 'object' and 'rules' can be nested s-exps.
The first element of each s-expr at any level should be an atom,
which we'll usually call the 'label'.
(I say 'usually' because there's an exception:
if the expression includes a color directive,
as described below, then that precedes the label.
Both the color directive and the label are atoms.)
The rest of the list can be anything.
The leaf-lists (lists with no sublists) of a rule
contain, after the label, a series of symbols,
 which will be concatenated in the result with ':' between them.
.
Consider such a leaf-list in a rule, with two elts, 'a' and 'b'.
The rules indicates how to transform 'a' into 'b'.
('a' is a label in the rule but is an atom in the object.)
If the transformation applies, it is appended to the output expression.
The transformation only applies if the atom 'a' from 'rules'
can be found in 'object', and both are nested such that
the sequence of 'label's leading to each is the same.
  So for instance if object=(a (b c)) and rules=(a (b (c d))),
  the output would be 'd', but if rules had been (b (a (c d)))
  the output would instead be the empty list.
  (In the first case if the rule were instead '(a (b (c d e)))',
  the output would be 'd:e'.)
.
There are several keywords that receive special treatment:
the colours RED, GREEN, BLUE, YELLOW, and ORANGE; the sexp-
shape markers ANY and IT; the positional marker ABUT; and the
directive INTERC. Each is described below.
.
ANY indicates that the path of labels exists.
Regardless of what the leaf sexp in the object at that path contains,
the elements listed after ANY in the corresponding leaf-sexp
of the rule will be appended to the output. This is true
even if the object leaf-sexp is a singleton,
containing only the label.
  So for instance, if our rule is (a (b (ANY x))),
  the output would be (x) for any of the following objects:
    (a (b))
    (a (b c))
    (a c (b c))
  whereas for these objects, the output would be ():
    (b a)
    (a b)
    (a)
.
In an ANY leaf-sexp in a rule,
IT refers to any value found after the label
of the corresponding leaf-sexp in 'object'.
Outside of an ANY leaf-sexp in a rule, IT is meaningless.
  So for instance:
    object = (a (b c))
    rule = (a (b (ANY x IT y)))
    output = (x:c:y)
  Note that a single IT can match multiple values:
    object = (a (b c d))
    rule = (a (b (ANY x IT y)))
    output = (x:c:y x:d:y)
.
RED, GREEN, BLUE, YELLOW, and ORANGE are color keywords that
can appear as the first element of any rule list, before the
label. They set the color for all output generated by that rule
and any nested rules, unless overridden by a deeper color keyword.
The color is applied as an `skg-color' text property on the
output string; a renderer maps that to a face at display time.
  For example, if
    rule = (a (RED b (c d) (GREEN e f))),
    then any 'd' produced by the rule will be red,
    but any 'f' produced by the rule will be green.
.
ABUT is a marker that may appear immediately after a leaf rule's
label (and optional color). A token emitted by an ABUT rule
carries an `skg-abut' property on its first character. Renderers
treat that as a signal to join the token to its predecessor with
no separator. Typical use: gluing a modifier character onto the
token it decorates (e.g. a peace symbol onto a birth character).
.
INTERC is a directive for rules of the form
    ([COLOR] INTERC SEP [LABEL] [PREFIX...] SUB-RULES...)
with SLOT semantics: each list sub-rule contributes exactly one
slot whose content is the concatenation of that sub-rule's
outputs (or the empty string if the sub-rule doesn't fire).
Slots are joined with SEP, the literal string PREFIX is
prepended, and the result is emitted as a single token. If every
slot is empty, no token is emitted.
  LABEL is optional: with it, INTERC matches children of OBJECT
  bearing that label; without it, it runs its sub-rules against
  OBJECT directly (useful when server-side atoms already sit at
  the current level).
  Per-sub-rule colors are preserved on the output string's
  character ranges; SEP and PREFIX take INTERC's own color.
.
A leaf-list in a rule can be vacuous, a singleton label.
This is just to demonstrate that the possibility has been considered,
and does not affect the output.
Such singleton leaf-lists can be omitted from the rule to no effect."
  (let ((header (and (listp rules) (skg--rule-header rules))))
    (if (or (not (listp object))
            (not header)
            (not (equal (car object) (alist-get 'label header))))
        '()
      (skg--transform-sexp-flat-from object header nil))))

(defun skg--propertize-color (s color)
  "Return a copy of S with `skg-color' set to COLOR over its full
range. Returns S unchanged when COLOR is nil or S is empty. The
engine uses `skg-color' as the neutral representation of
\"colour\" on tokens; a rendering layer (for heralds, that's
`heralds--tokens->text') converts it to a face at display time."
  (let ((copy (copy-sequence s)))
    (when (and color (> (length copy) 0))
      (put-text-property 0 (length copy) 'skg-color color copy))
    copy))

(defun skg--tokens->string
  (tokens
    current-color)
  "Join TOKENS with `:' and propertize the result with CURRENT-COLOR."
  (skg--propertize-color
   (mapconcat #'skg--token->string tokens ":")
   current-color))

(defun skg--token->string
  (token)
  "Convert TOKEN to string. Symbols and strings are common (rule
child labels); numbers reach here via ANY/IT matches on numeric
atoms in the input (e.g. counts like `(containers 3)'). Anything
else is `format'-ed as a last resort."
  (cond
    ((symbolp token) (symbol-name token))
    ((stringp token) token)
    (t (format "%s" token))))

(defun skg--color-keyword-p
  (sym)
  "Return t if SYM is a color keyword (RED, GREEN, BLUE, YELLOW, ORANGE)."
  (memq sym '(RED GREEN BLUE YELLOW ORANGE)))

(defun skg--rule-header (rule)
  "Parse RULE once and return an alist classifying it.
Keys:
  kind      -- one of `interc', `any-leaf', `atomic-leaf', `non-leaf'.
  color     -- the color keyword at the rule's head, or nil.
  label     -- the rule's label symbol (required for non-INTERC;
               optional for INTERC).
  separator -- INTERC's separator string, or nil for non-INTERC.
  abut      -- t if the rule carries an ABUT marker (leaf-only).
  children  -- the rule's post-header tail: literal strings are
               prefix material, list children are sub-rules to
               recurse into.

Grammar handled:
  RULE        ::= [COLOR] (INTERC-BODY | SIMPLE-BODY)
  INTERC-BODY ::= INTERC SEP [LABEL] CHILDREN...
  SIMPLE-BODY ::= LABEL [ABUT] CHILDREN...

Classification for simple bodies: `non-leaf' if any child is a
list; `any-leaf' if label is ANY (and it's a leaf);
`atomic-leaf' otherwise."
  (let ((tail rule)
        (color nil)
        (kind nil)
        (label nil)
        (separator nil)
        (abut nil)
        (children nil))
    (when (and (consp tail) (skg--color-keyword-p (car tail)))
      (setq color (car tail))
      (setq tail (cdr tail)))
    (cond
      ((eq (car-safe tail) 'INTERC)
       (setq kind 'interc)
       (setq tail (cdr tail))
       (setq separator (car tail))
       (setq tail (cdr tail))
       (when (and (consp tail)
                  (symbolp (car tail))
                  (car tail)
                  (not (skg--color-keyword-p (car tail))))
         (setq label (car tail))
         (setq tail (cdr tail)))
       (setq children tail))
      (t
       (setq label (car-safe tail))
       (setq tail (cdr tail))
       (when (eq (car-safe tail) 'ABUT)
         (setq abut t)
         (setq tail (cdr tail)))
       (setq children tail)
       (setq kind
             (cond
               ((cl-some #'listp children) 'non-leaf)
               ((eq label 'ANY)            'any-leaf)
               (t                          'atomic-leaf)))))
    (list (cons 'kind kind)
          (cons 'color color)
          (cons 'label label)
          (cons 'separator separator)
          (cons 'abut abut)
          (cons 'children children))))

(defun skg--transform-sexp-flat-from
  (object
    header
    current-color)
  "Transform OBJECT using HEADER (a parsed rule) with CURRENT-COLOR.
String-literal children of the header are collected into a prefix.
When any list child fires, the prefix is concatenated (no
separator) before each of its outputs. When no list child fires
but the prefix is non-empty, the prefix is emitted alone -- so
rules like (RED deleted \"DELETED\" (id) (source)) serve as a
label for the structure even when their sub-rules are vacuous."
  (let* ((new-color
           (or (alist-get 'color header) current-color))
         (children (alist-get 'children header))
         (prefix
           (mapconcat
             #'identity
             (cl-remove-if-not #'stringp children)
             ""))
         (results '()))
    (dolist (rc children)
      (when (listp rc)
        (setq results
              (nconc results
                     (skg--transform-sexp-flat-dispatch
                      object rc new-color)))))
    (cond
      ((string-empty-p prefix) results)
      ((null results)
       (list (skg--prepend-prefix "" prefix new-color)))
      (t
       (mapcar
         (lambda (r) (skg--prepend-prefix r prefix new-color))
         results)))))

(defun skg--prepend-prefix
  (output prefix color)
  "Return PREFIX concatenated with OUTPUT. PREFIX carries COLOR
via `skg-color'; OUTPUT's own text properties are preserved."
  (concat (skg--propertize-color prefix color) output))

(defun skg--transform-sexp-flat-dispatch
  (object
    rule-child
    current-color)
  "Dispatch RULE-CHILD application to OBJECT with CURRENT-COLOR.
Parses RULE-CHILD's header exactly once and pcases on kind."
  (if (not (listp rule-child))
      '()
    (let ((header (skg--rule-header rule-child)))
      (pcase (alist-get 'kind header)
        ('interc      (skg--apply-interc        object header current-color))
        ('any-leaf    (skg--apply-any-leaf      object header current-color))
        ('atomic-leaf (skg--apply-ordinary-leaf object header current-color))
        ('non-leaf    (skg--apply-non-leaf      object header current-color))))))

(defun skg--apply-interc
  (object header current-color)
  "Apply an INTERC HEADER to OBJECT with CURRENT-COLOR.

Two modes depending on whether the rule has a LABEL:

- With LABEL: for each child of OBJECT matching that label, run
  the sub-rules against it and emit one combined token.
- Without LABEL: run the sub-rules against OBJECT itself and emit
  at most one combined token. Used when the server already emits
  the raw atoms at the current level (e.g. `(containers N)' and
  `(contents M)' as siblings inside `(graphStats ...)') and no
  wrapper form is needed.

In both modes, each sub-rule contributes one slot; slots are
joined with the header's SEPARATOR; a literal-string prefix is
prepended; the token is suppressed if every slot is empty.

Colors: the separator and prefix take the rule's inherited color
context (its own color if set, otherwise CURRENT-COLOR). Each
slot preserves whatever colors its sub-rule's outputs carry, via
text properties on character ranges."
  (let* ((new-color (or (alist-get 'color header) current-color))
         (sep       (alist-get 'separator header))
         (label     (alist-get 'label header))
         (children  (alist-get 'children header))
         (prefix-str (mapconcat #'identity
                       (cl-remove-if-not #'stringp children) ""))
         (targets (if label
                      (skg--object-children-with-label object label)
                    (list object)))
         (results '()))
    (dolist (target targets)
      (let ((slots '()))
        (dolist (rc children)
          (when (listp rc)
            (let ((outs (skg--transform-sexp-flat-dispatch
                         target rc new-color)))
              (push (apply #'concat outs) slots))))
        (setq slots (nreverse slots))
        (when (cl-some (lambda (s) (> (length s) 0)) slots)
          (push (skg--interc--build-token
                 prefix-str sep slots new-color)
                results))))
    (nreverse results)))

(defun skg--interc--build-token (prefix sep slots color)
  "Build an INTERC token: PREFIX + JOIN(SLOTS, SEP).
PREFIX and SEP both carry COLOR via `skg-color'. Each slot
string's own text properties survive the concatenation, so
per-sub-rule colors remain visible as ranges on the final token."
  (let ((out (skg--propertize-color prefix color))
        (first t))
    (dolist (slot slots)
      (unless first
        (setq out (concat out
                          (skg--propertize-color sep color))))
      (setq out (concat out slot))
      (setq first nil))
    out))

(defun skg--apply-non-leaf
  (object
    header
    current-color)
  "Apply non-leaf HEADER to OBJECT with CURRENT-COLOR."
  (let
      ((matches
          (skg--object-children-with-label
            object (alist-get 'label header)))
        (results '()))
    (dolist
        (match matches)
      (setq results
            (nconc results
                   (skg--transform-sexp-flat-from
                    match header current-color))))
    results))

(defun skg--apply-ordinary-leaf
  (object
    header
    current-color)
  "Apply ordinary leaf HEADER to OBJECT with CURRENT-COLOR."
  (let*
      ((color   (or (alist-get 'color header) current-color))
       (label   (alist-get 'label header))
       (abut    (alist-get 'abut header))
       (tokens  (alist-get 'children header))
       (matches (skg--object-atomic-matches object label))
       (results '()))
    (when tokens
      (dolist
          (_ matches)
        (let ((tok (skg--tokens->string tokens color)))
          (skg--maybe-mark-abut tok abut)
          (setq results (nconc results (list tok))))))
    results))

(defun skg--apply-any-leaf
  (object
    header
    current-color)
  "Apply ANY leaf HEADER to OBJECT with CURRENT-COLOR."
  (let*
      ((color       (or (alist-get 'color header) current-color))
       (abut        (alist-get 'abut header))
       (tokens      (alist-get 'children header))
       (tail-values (cdr object))
       (results '()))
    (cond
      ((null tokens) '())
      ((memq 'IT tokens)
        (dolist
            (tail-value tail-values)
          (let ((tok (skg--tokens->string
                      (skg--replace-it tokens tail-value) color)))
            (skg--maybe-mark-abut tok abut)
            (setq results (nconc results (list tok)))))
        results)
      (t
        (let ((tok (skg--tokens->string tokens color)))
          (skg--maybe-mark-abut tok abut)
          (list tok))))))

(defun skg--maybe-mark-abut (tok abut)
  "If ABUT is non-nil and TOK is a non-empty string, set the
`skg-abut' text property on its first character. Renderers read
that property to decide whether to emit a separator before TOK."
  (when (and abut (stringp tok) (> (length tok) 0))
    (put-text-property 0 1 'skg-abut t tok)))

(defun skg--replace-it
  (tokens
    tail-value)
  (mapcar
    (lambda
      (token)
      (if
          (eq token 'IT)
          tail-value
        token))
    tokens))

(defun skg--object-children-with-label
  (object
    label)
  (cl-loop
    for element in (cdr object)
    when
    (and
      (listp element)
      (equal (car element) label))
    collect element))

(defun skg--object-atomic-matches
  (object
    label)
  (cl-loop
    for element in (cdr object)
    when
    (and
      (not (listp element))
      (equal element label))
    collect element))

(provide 'skg-lens)
