;;; test-skg-strip-command.el --- strip command wire identity -*- lexical-binding: t; -*-

(require 'ert)
(add-to-list 'load-path (expand-file-name "../../elisp" default-directory))
(require 'skg-request-strip-body-whitespace)

(ert-deftest test-skg-strip-body-whitespace-wire-has-operation-and-session ()
  (let ((skg--server-session-id "11111111-2222-4333-8444-555555555555")
        (skg-rust-tcp-proc 'process)
        wires)
    (cl-letf (((symbol-function 'skg-tcp-connect-to-rust)
               (lambda () 'process))
              ((symbol-function 'process-live-p) (lambda (_) t))
              ((symbol-function 'skg-connection-handshake-ensure)
               (lambda () t))
              ((symbol-function 'skg-register-response-handler)
               (lambda (&rest _) nil))
              ((symbol-function 'skg-submit-request)
               (lambda (_tcp wire) (push wire wires))))
      (skg-strip-trailing-whitespace-from-bodies)
      (skg-strip-trailing-whitespace-from-bodies))
    (let ((first (read (car wires)))
          (second (read (cadr wires))))
      (should (equal (cdr (assq 'server-session-id first))
                     skg--server-session-id))
      (should (equal (cdr (assq 'server-session-id second))
                     skg--server-session-id))
      (should (cdr (assq 'operation-id first)))
      (should (cdr (assq 'operation-id second)))
      (should-not (equal (cdr (assq 'operation-id first))
                         (cdr (assq 'operation-id second)))))))
