;;; test-skg-view-id.el --- Tests for skg-view-id permanent-local behavior

(load-file (expand-file-name "../../elisp/skg-test-utils.el"
                             (file-name-directory load-file-name)))
(require 'ert)
(require 'skg-buffer)

(defun test--make-skg-buffer (name content &optional view-id)
  "Create an skg buffer via skg-open-org-buffer-from-text."
  (skg-open-org-buffer-from-text nil content name view-id))

(ert-deftest test-view-id-set-on-creation ()
  "skg-open-org-buffer-from-text sets skg-view-id and enables content-view-mode."
  (let ((buf (test--make-skg-buffer
              "*test-view-id-set*" "* hello\n" "test-view-id-123")))
    (unwind-protect
        (with-current-buffer buf
          (should (equal skg-view-id "test-view-id-123"))
          (should (derived-mode-p 'skg-content-view-mode)))
      (kill-buffer buf))))

(ert-deftest test-view-id-autogenerated-when-omitted ()
  "skg-view-id is a non-empty string even when no explicit VIEW-ID is given."
  (let ((buf (test--make-skg-buffer
              "*test-view-id-auto*" "* hello\n")))
    (unwind-protect
        (with-current-buffer buf
          (should (stringp skg-view-id))
          (should (> (length skg-view-id) 8)))
      (kill-buffer buf))))

(ert-deftest test-view-id-survives-org-mode ()
  "skg-view-id (permanent-local) survives org-mode re-activation."
  (let ((buf (test--make-skg-buffer
              "*test-view-id-orgmode*" "* hello\n" "view-id-before")))
    (unwind-protect
        (with-current-buffer buf
          (org-mode)
          (should (equal skg-view-id "view-id-before")))
      (kill-buffer buf))))

(ert-deftest test-content-view-mode-killed-by-org-mode ()
  "skg-content-view-mode (not permanent-local) is killed by org-mode."
  (let ((buf (test--make-skg-buffer
              "*test-mode-orgmode*" "* hello\n" "view-id-x")))
    (unwind-protect
        (with-current-buffer buf
          (should (derived-mode-p 'skg-content-view-mode))
          (org-mode)
          (should-not (derived-mode-p 'skg-content-view-mode)))
      (kill-buffer buf))))

(ert-deftest test-view-id-survives-fundamental-mode ()
  "skg-view-id (permanent-local) survives fundamental-mode."
  (let ((buf (test--make-skg-buffer
              "*test-view-id-fund*" "* hello\n" "view-id-fund")))
    (unwind-protect
        (with-current-buffer buf
          (fundamental-mode)
          (should (equal skg-view-id "view-id-fund")))
      (kill-buffer buf))))

(ert-deftest test-view-id-survives-erase-and-insert ()
  "skg-view-id survives erase-buffer + insert (the save-response path)."
  (let ((buf (test--make-skg-buffer
              "*test-view-id-erase*" "* hello\n" "view-id-erase")))
    (unwind-protect
        (with-current-buffer buf
          (let ((inhibit-read-only t))
            (erase-buffer)
            (insert "* completely new content\n"))
          (should (equal skg-view-id "view-id-erase")))
      (kill-buffer buf))))

(ert-deftest test-view-id-gone-after-kill-and-recreate ()
  "A buffer killed and recreated with the same name has no skg-view-id."
  (let ((buf (test--make-skg-buffer
              "*test-view-id-recreate*" "* hello\n" "view-id-old")))
    (kill-buffer buf)
    (let ((new-buf (get-buffer-create "*test-view-id-recreate*")))
      (unwind-protect
          (with-current-buffer new-buf
            (should-not skg-view-id)
            (should-not (derived-mode-p 'skg-content-view-mode)))
        (kill-buffer new-buf)))))

(ert-deftest test-view-id-stale-after-partial-reopen ()
  "If org-mode runs but skg-view-id is never re-set, the old VIEW-ID persists
but skg-content-view-mode is lost."
  (let ((buf (test--make-skg-buffer
              "*test-view-id-partial*" "* hello\n" "view-id-original")))
    (unwind-protect
        (with-current-buffer buf
          (let ((inhibit-read-only t))
            (erase-buffer)
            (insert "* new content\n")
            (org-mode))
          (should (equal skg-view-id "view-id-original"))
          (should-not (derived-mode-p 'skg-content-view-mode)))
      (kill-buffer buf))))

(ert-deftest test-view-id-survives-revert-buffer ()
  "skg-view-id survives revert-buffer on a non-file buffer."
  (let ((buf (test--make-skg-buffer
              "*test-view-id-revert*" "* hello\n" "view-id-revert")))
    (unwind-protect
        (with-current-buffer buf
          (condition-case nil
              (revert-buffer t t)
            (error nil))
          (should (equal skg-view-id "view-id-revert")))
      (kill-buffer buf))))

(ert-deftest test-view-id-survives-rename-buffer ()
  "skg-view-id survives rename-buffer."
  (let ((buf (test--make-skg-buffer
              "*test-view-id-rename*" "* hello\n" "view-id-rename")))
    (unwind-protect
        (with-current-buffer buf
          (rename-buffer "*test-view-id-renamed*")
          (should (equal skg-view-id "view-id-rename")))
      (kill-buffer buf))))

(ert-deftest test-same-name-content-views-do-not-overwrite-each-other ()
  "A same-name view gets a numeric suffix when repos cannot distinguish it."
  (let (first second)
    (unwind-protect
        (progn
          (setq first (test--make-skg-buffer
                       "*same-title*" "* first\n" "view-id-first"))
          (setq second (test--make-skg-buffer
                        "*same-title*" "* second\n" "view-id-second"))
          (should-not (eq first second))
          (should (equal (buffer-name first) "*same-title*"))
          (should (equal (buffer-name second) "*same-title*<2>"))
          (with-current-buffer first
            (should (equal (buffer-string) "* first\n"))
            (should (equal skg-view-id "view-id-first")))
          (with-current-buffer second
            (should (equal (buffer-string) "* second\n"))
            (should (equal skg-view-id "view-id-second"))))
      (when (buffer-live-p first) (kill-buffer first))
      (when (buffer-live-p second) (kill-buffer second)))))

(ert-deftest test-same-title-different-repos-qualify-both-buffer-names ()
  "Different root repos are more informative than numeric suffixes."
  (let (public cheese)
    (unwind-protect
        (progn
          (setq public
                (test--make-skg-buffer
                 "*cooking*"
                 "* (skg (node (id public-id) (repo public))) cooking\n"
                 "view-id-public"))
          (setq cheese
                (test--make-skg-buffer
                 "*cooking*"
                 "* (skg (node (id cheese-id) (repo Cheese))) cooking\n"
                 "view-id-cheese"))
          (should (equal (buffer-name public) "*cooking* <public>"))
          (should (equal (buffer-name cheese) "*cooking* <Cheese>"))
          (should (equal (buffer-local-value 'skg-view-id public)
                         "view-id-public"))
          (should (equal (buffer-local-value 'skg-view-id cheese)
                         "view-id-cheese")))
      (when (buffer-live-p public) (kill-buffer public))
      (when (buffer-live-p cheese) (kill-buffer cheese)))))

(ert-deftest test-content-view-does-not-erase-unrelated-same-name-buffer ()
  (let ((unrelated (generate-new-buffer "*occupied-title*"))
        opened)
    (unwind-protect
        (progn
          (with-current-buffer unrelated (insert "keep me"))
          (setq opened
                (test--make-skg-buffer
                 "*occupied-title*"
                 "* (skg (node (id x) (repo public))) occupied title\n"
                 "view-id-new"))
          (should-not (eq unrelated opened))
          (should (equal (buffer-name opened) "*occupied-title*<2>"))
          (with-current-buffer unrelated
            (should (equal (buffer-string) "keep me"))
            (should-not skg-view-id)))
      (when (buffer-live-p unrelated) (kill-buffer unrelated))
      (when (buffer-live-p opened) (kill-buffer opened)))))

(provide 'test-skg-view-id)
