;;; test-skg-view-uri.el --- Tests for skg-view-uri permanent-local behavior

(load-file (expand-file-name "../../elisp/skg-test-utils.el"
                             (file-name-directory load-file-name)))
(require 'ert)
(require 'skg-buffer)

(defun test--make-skg-buffer (name content &optional uri)
  "Create an skg buffer via skg-open-org-buffer-from-text."
  (skg-open-org-buffer-from-text nil content name uri))

(ert-deftest test-view-uri-set-on-creation ()
  "skg-open-org-buffer-from-text sets skg-view-uri and enables content-view-mode."
  (let ((buf (test--make-skg-buffer
              "*test-uri-set*" "* hello\n" "test-uri-123")))
    (unwind-protect
        (with-current-buffer buf
          (should (equal skg-view-uri "test-uri-123"))
          (should (derived-mode-p 'skg-content-view-mode)))
      (kill-buffer buf))))

(ert-deftest test-view-record-exists-before-herald-setup ()
  "Nested work started by herald setup sees a complete application record."
  (let ((skg--buffer-registry (make-hash-table :test #'equal))
        (skg--server-store-state '((graph-generation . 1)))
        seen-record
        buf)
    (unwind-protect
        (cl-letf (((symbol-function 'heralds-minor-mode)
                   (lambda () (setq seen-record skg--buffer-record))))
          (setq buf (test--make-skg-buffer
                     "*test-herald-record-order*" "* hello\n" "order-uri"))
          (should seen-record)
          (should (equal "order-uri"
                         (skg--buffer-record-view-uri seen-record))))
      (when (buffer-live-p buf) (kill-buffer buf)))))

(ert-deftest test-view-uri-autogenerated-when-omitted ()
  "skg-view-uri is a non-empty string even when no explicit URI is given."
  (let ((buf (test--make-skg-buffer
              "*test-uri-auto*" "* hello\n")))
    (unwind-protect
        (with-current-buffer buf
          (should (stringp skg-view-uri))
          (should (> (length skg-view-uri) 8)))
      (kill-buffer buf))))

(ert-deftest test-view-uri-survives-org-mode ()
  "skg-view-uri (permanent-local) survives org-mode re-activation."
  (let ((buf (test--make-skg-buffer
              "*test-uri-orgmode*" "* hello\n" "uri-before")))
    (unwind-protect
        (with-current-buffer buf
          (org-mode)
          (should (equal skg-view-uri "uri-before")))
      (kill-buffer buf))))

(ert-deftest test-content-view-mode-killed-by-org-mode ()
  "skg-content-view-mode (not permanent-local) is killed by org-mode."
  (let ((buf (test--make-skg-buffer
              "*test-mode-orgmode*" "* hello\n" "uri-x")))
    (unwind-protect
        (with-current-buffer buf
          (should (derived-mode-p 'skg-content-view-mode))
          (org-mode)
          (should-not (derived-mode-p 'skg-content-view-mode)))
      (kill-buffer buf))))

(ert-deftest test-view-uri-survives-fundamental-mode ()
  "skg-view-uri (permanent-local) survives fundamental-mode."
  (let ((buf (test--make-skg-buffer
              "*test-uri-fund*" "* hello\n" "uri-fund")))
    (unwind-protect
        (with-current-buffer buf
          (fundamental-mode)
          (should (equal skg-view-uri "uri-fund")))
      (kill-buffer buf))))

(ert-deftest test-view-uri-survives-erase-and-insert ()
  "skg-view-uri survives erase-buffer + insert (the save-response path)."
  (let ((buf (test--make-skg-buffer
              "*test-uri-erase*" "* hello\n" "uri-erase")))
    (unwind-protect
        (with-current-buffer buf
          (let ((inhibit-read-only t))
            (erase-buffer)
            (insert "* completely new content\n"))
          (should (equal skg-view-uri "uri-erase")))
      (kill-buffer buf))))

(ert-deftest test-view-uri-gone-after-kill-and-recreate ()
  "A buffer killed and recreated with the same name has no skg-view-uri."
  (let ((buf (test--make-skg-buffer
              "*test-uri-recreate*" "* hello\n" "uri-old")))
    (kill-buffer buf)
    (let ((new-buf (get-buffer-create "*test-uri-recreate*")))
      (unwind-protect
          (with-current-buffer new-buf
            (should-not skg-view-uri)
            (should-not (derived-mode-p 'skg-content-view-mode)))
        (kill-buffer new-buf)))))

(ert-deftest test-view-uri-stale-after-partial-reopen ()
  "If org-mode runs but skg-view-uri is never re-set, the old URI persists
but skg-content-view-mode is lost."
  (let ((buf (test--make-skg-buffer
              "*test-uri-partial*" "* hello\n" "uri-original")))
    (unwind-protect
        (with-current-buffer buf
          (let ((inhibit-read-only t))
            (erase-buffer)
            (insert "* new content\n")
            (org-mode))
          (should (equal skg-view-uri "uri-original"))
          (should-not (derived-mode-p 'skg-content-view-mode)))
      (kill-buffer buf))))

(ert-deftest test-view-uri-survives-revert-buffer ()
  "skg-view-uri survives revert-buffer on a non-file buffer."
  (let ((buf (test--make-skg-buffer
              "*test-uri-revert*" "* hello\n" "uri-revert")))
    (unwind-protect
        (with-current-buffer buf
          (condition-case nil
              (revert-buffer t t)
            (error nil))
          (should (equal skg-view-uri "uri-revert")))
      (kill-buffer buf))))

(ert-deftest test-view-uri-survives-rename-buffer ()
  "skg-view-uri survives rename-buffer."
  (let ((buf (test--make-skg-buffer
              "*test-uri-rename*" "* hello\n" "uri-rename")))
    (unwind-protect
        (with-current-buffer buf
          (rename-buffer "*test-uri-renamed*")
          (should (equal skg-view-uri "uri-rename")))
      (kill-buffer buf))))

(ert-deftest test-same-name-content-views-do-not-overwrite-each-other ()
  "A same-name view gets a numeric suffix when sources cannot distinguish it."
  (let (first second)
    (unwind-protect
        (progn
          (setq first (test--make-skg-buffer
                       "*same-title*" "* first\n" "uri-first"))
          (setq second (test--make-skg-buffer
                        "*same-title*" "* second\n" "uri-second"))
          (should-not (eq first second))
          (should (equal (buffer-name first) "*same-title*"))
          (should (equal (buffer-name second) "*same-title*<2>"))
          (with-current-buffer first
            (should (equal (buffer-string) "* first\n"))
            (should (equal skg-view-uri "uri-first")))
          (with-current-buffer second
            (should (equal (buffer-string) "* second\n"))
            (should (equal skg-view-uri "uri-second"))))
      (when (buffer-live-p first) (kill-buffer first))
      (when (buffer-live-p second) (kill-buffer second)))))

(ert-deftest test-same-title-different-sources-qualify-both-buffer-names ()
  "Different root sources are more informative than numeric suffixes."
  (let (public cheese)
    (unwind-protect
        (progn
          (setq public
                (test--make-skg-buffer
                 "*cooking*"
                 "* (skg (node (id public-id) (source public))) cooking\n"
                 "uri-public"))
          (setq cheese
                (test--make-skg-buffer
                 "*cooking*"
                 "* (skg (node (id cheese-id) (source Cheese))) cooking\n"
                 "uri-cheese"))
          (should (equal (buffer-name public) "*cooking* <public>"))
          (should (equal (buffer-name cheese) "*cooking* <Cheese>"))
          (should (equal (buffer-local-value 'skg-view-uri public)
                         "uri-public"))
          (should (equal (buffer-local-value 'skg-view-uri cheese)
                         "uri-cheese")))
      (when (buffer-live-p public) (kill-buffer public))
      (when (buffer-live-p cheese) (kill-buffer cheese)))))

(ert-deftest test-content-view-does-not-erase-unrelated-same-name-buffer ()
  (let ((unrelated (generate-new-buffer "*occupied-title*"))
        opened)
    (unwind-protect
        (progn
          (with-current-buffer unrelated (insert "keep me"))
          (setq opened
                (test--make-skg-buffer
                 "*occupied-title*"
                 "* (skg (node (id x) (source public))) occupied title\n"
                 "uri-new"))
          (should-not (eq unrelated opened))
          (should (equal (buffer-name opened) "*occupied-title*<2>"))
          (with-current-buffer unrelated
            (should (equal (buffer-string) "keep me"))
            (should-not skg-view-uri)))
      (when (buffer-live-p unrelated) (kill-buffer unrelated))
      (when (buffer-live-p opened) (kill-buffer opened)))))

(provide 'test-skg-view-uri)
