-- PURPOSE: 'git add' new .skg files in a subtree, but only when each
-- file is not yet known to git at all (untracked, not even in the
-- index). "Not in the index" (rather than "not in HEAD") is the
-- predicate, so a previously-staged-but-modified file is NOT
-- re-added: the command's job is to make the file exist in git
-- history, a one-time thing. Path resolution happens entirely
-- client-side (skg.config), so the recursive scan needs no server
-- round-trip per node. The Lua port of elisp/skg-git-add.el, with one
-- shape change: the preview is a SHELL script rather than executable
-- elisp, since there is no Lua reader-executor idiom worth teaching
-- users; the non-preview command runs the same per-file logic
-- directly.

local config = require('skg.config')
local focus = require('skg.focus')
local id_search = require('skg.id_search')
local metadata = require('skg.metadata')
local sexpr = require('skg.sexpr.parse')

local M = {}

---Run the git-add plan without showing it (for once you trust the
---preview).
function M.git_add_if_new_recursive ()
  local plan = M.git_add_new_files_recursive_plan()
  local added = 0
  for _, group in ipairs(plan.groups) do
    for _, file in ipairs(group.files) do
      if not M.file_known_to_git(group.dir, file) then
        vim.fn.system({ 'git', '-C', group.dir, 'add', '--', file })
        added = added + 1
      end
    end
  end
  vim.notify(string.format(
    'git_add_if_new_recursive: ran git-add for %d new file(s)'
    .. ' (%d actually added)', #plan.paths, added))
end

---Show a reviewable shell script that stages new files in the current
---subtree. Each file is rechecked against the git index before
---staging, so running the script later will not stage modifications
---to files that became known to git in the meantime.
function M.git_add_if_new_recursive_preview ()
  local plan = M.git_add_new_files_recursive_plan()
  local name = 'skg://git-add-new-files'
  local buf = nil
  for _, existing in ipairs(vim.api.nvim_list_bufs()) do
    if vim.api.nvim_buf_get_name(existing) == name then
      buf = existing break end
  end
  if not buf then
    buf = vim.api.nvim_create_buf(true, true)
    vim.api.nvim_buf_set_name(buf, name)
  end
  vim.bo[buf].modifiable = true
  vim.api.nvim_buf_set_lines(buf, 0, -1, false,
                             vim.split(plan.script, '\n'))
  vim.bo[buf].filetype = 'sh'
  vim.bo[buf].modified = false
  vim.api.nvim_set_current_buf(buf)
  require('skg.readable_ids').enable(buf)
  vim.notify(string.format(
    'git_add_if_new_recursive_preview: %d new file(s)', #plan.paths))
end

---@param dir string
---@param file string
---@return boolean is FILE already in DIR's git index?
function M.file_known_to_git (dir, file)
  vim.fn.system({ 'git', '-C', dir, 'ls-files', '--error-unmatch',
                  file })
  return vim.v.shell_error == 0
end

---The git-add plan for new files in this subtree: absolute paths,
---their by-directory grouping, and the reviewable script.
---@return table {paths, groups, script}
function M.git_add_new_files_recursive_plan ()
  local pairs_found = M.subtree_unstaged_new_file_pairs()
  local paths = {}
  local seen = {}
  for _, pair in ipairs(pairs_found) do
    local path = config.abs_path_for_id_and_source(pair[1], pair[2])
    if path and not seen[path] then
      seen[path] = true
      table.insert(paths, path)
    end
  end
  local groups = M.group_paths_by_dir(paths)
  return { paths = paths, groups = groups,
           script = M.git_add_script(groups) }
end

---@param groups table[]
---@return string a shell script staging each still-unknown file
function M.git_add_script (groups)
  if #groups == 0 then
    return '# No unstaged new skg files found in this subtree.' end
  local lines = {
    '# Stages each listed .skg file unless git already knows it',
    '# (present in the index); a staged-but-modified file is left',
    '# alone. Generated by :SkgGitAddIfNewRecursivePreview.' }
  for _, group in ipairs(groups) do
    table.insert(lines, '')
    table.insert(lines,
                 string.format('cd %s', vim.fn.shellescape(group.dir)))
    for _, file in ipairs(group.files) do
      local quoted = vim.fn.shellescape(file)
      table.insert(lines, string.format(
        'git ls-files --error-unmatch %s >/dev/null 2>&1 || '
        .. 'git add -- %s', quoted, quoted))
    end
  end
  return table.concat(lines, '\n')
end

---Group PATHS by directory, preserving first-seen directory order.
---@param paths string[]
---@return table[] each {dir, files}
function M.group_paths_by_dir (paths)
  local groups = {}
  local by_dir = {}
  for _, path in ipairs(paths) do
    local dir = vim.fn.fnamemodify(path, ':h')
    local file = vim.fn.fnamemodify(path, ':t')
    if not by_dir[dir] then
      by_dir[dir] = { dir = dir, files = {} }
      table.insert(groups, by_dir[dir])
    end
    table.insert(by_dir[dir].files, file)
  end
  return groups
end

---{id, source} pairs in this subtree whose metadata carries the
---unstaged newX axis (file-existence changes, not membership-only
---newM).
---@return table[]
function M.subtree_unstaged_new_file_pairs ()
  local start = focus.owning_headline_line()
  if not start then error('Not on a headline') end
  local last = M.subtree_last_line(start)
  local pairs_found = {}
  for line = start, last do
    local sexp = metadata.metadata_sexp_at_line_or_nil(line)
    if sexp and M.metadata_has_unstaged_new_file_p(sexp) then
      local id = id_search.extract_id_from_metadata_sexp(sexp)
      local source = id_search.extract_source_from_metadata_sexp(sexp)
      if id and source then
        table.insert(pairs_found, { id, source }) end
    end
  end
  return pairs_found
end

---@param start integer a headline
---@return integer the subtree's last line
function M.subtree_last_line (start)
  local after = metadata.next_heading_after_subtree(start)
  if after then return after - 1 end
  return vim.api.nvim_buf_line_count(0)
end

---@param sexp any
---@return boolean is SEXP an ActiveNode marked as a new worktree file?
function M.metadata_has_unstaged_new_file_p (sexp)
  local values = metadata.sexp_cdr_at_path(sexp,
                                           { 'skg', 'node', 'unstaged' })
  for _, value in ipairs(values or {}) do
    if value == sexpr.symbol('newX') then return true end
  end
  return false
end

return M
